/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useTrimeshCollision } from "spacesvr";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    vox001_1: THREE.Mesh
    vox001_2: THREE.Mesh
    vox001_3: THREE.Mesh
    vox001_4: THREE.Mesh
    vox001_5: THREE.Mesh
    vox001_6: THREE.Mesh
    vox001_7: THREE.Mesh
    vox001_8: THREE.Mesh
    vox001_9: THREE.Mesh
    vox001_10: THREE.Mesh
    vox001_11: THREE.Mesh
    vox001_12: THREE.Mesh
    vox001_13: THREE.Mesh
    vox001_14: THREE.Mesh
    vox001_15: THREE.Mesh
    vox001_16: THREE.Mesh
    vox001_17: THREE.Mesh
    vox002_1: THREE.Mesh
    vox002_2: THREE.Mesh
    vox002_3: THREE.Mesh
    vox002_4: THREE.Mesh
    vox002_5: THREE.Mesh
    vox002_6: THREE.Mesh
    vox002_7: THREE.Mesh
    vox002_8: THREE.Mesh
    vox002_9: THREE.Mesh
    vox002_10: THREE.Mesh
    vox002_11: THREE.Mesh
    vox002_12: THREE.Mesh
    vox002_13: THREE.Mesh
    vox002_14: THREE.Mesh
    vox002_15: THREE.Mesh
    vox002_16: THREE.Mesh
    vox002_17: THREE.Mesh
    vox002_18: THREE.Mesh
    vox003_1: THREE.Mesh
    vox003_2: THREE.Mesh
    vox003_3: THREE.Mesh
    vox004_1: THREE.Mesh
    vox004_2: THREE.Mesh
    vox004_3: THREE.Mesh
    vox004_4: THREE.Mesh
    vox004_5: THREE.Mesh
    vox004_6: THREE.Mesh
    vox004_7: THREE.Mesh
    vox004_8: THREE.Mesh
    vox004_9: THREE.Mesh
    vox004_10: THREE.Mesh
    vox004_11: THREE.Mesh
    vox004_12: THREE.Mesh
    vox004_13: THREE.Mesh
    vox004_14: THREE.Mesh
    vox004_15: THREE.Mesh
    vox004_16: THREE.Mesh
    vox005_1: THREE.Mesh
    vox005_2: THREE.Mesh
    vox005_3: THREE.Mesh
    vox120_1: THREE.Mesh
    vox120_2: THREE.Mesh
    vox120_3: THREE.Mesh
    vox120_4: THREE.Mesh
    vox120_5: THREE.Mesh
    vox120_6: THREE.Mesh
    vox121_1: THREE.Mesh
    vox121_2: THREE.Mesh
    vox121_3: THREE.Mesh
    vox121_4: THREE.Mesh
    vox121_5: THREE.Mesh
    vox121_6: THREE.Mesh
    vox121_7: THREE.Mesh
    vox121_8: THREE.Mesh
    vox121_9: THREE.Mesh
    vox121_10: THREE.Mesh
    vox121_11: THREE.Mesh
    vox121_12: THREE.Mesh
    vox121_13: THREE.Mesh
    vox291_1: THREE.Mesh
    vox291_2: THREE.Mesh
    vox291_3: THREE.Mesh
    vox291_4: THREE.Mesh
    vox291_5: THREE.Mesh
    vox291_6: THREE.Mesh
    vox291_7: THREE.Mesh
    vox291_8: THREE.Mesh
    vox291_9: THREE.Mesh
    vox291_10: THREE.Mesh
    vox291_11: THREE.Mesh
    vox291_12: THREE.Mesh
    vox291_13: THREE.Mesh
    vox291_14: THREE.Mesh
    vox291_15: THREE.Mesh
    vox291_16: THREE.Mesh
    vox291_17: THREE.Mesh
    vox291_18: THREE.Mesh
    vox291_19: THREE.Mesh
    vox291_20: THREE.Mesh
    vox291_21: THREE.Mesh
    vox291_22: THREE.Mesh
    vox291_23: THREE.Mesh
    vox291_24: THREE.Mesh
    vox291_25: THREE.Mesh
    vox291_26: THREE.Mesh
    vox291_27: THREE.Mesh
    vox291_28: THREE.Mesh
    vox291_29: THREE.Mesh
    vox291_30: THREE.Mesh
    vox291_31: THREE.Mesh
    vox291_32: THREE.Mesh
    vox291_33: THREE.Mesh
    vox291_34: THREE.Mesh
    vox291_35: THREE.Mesh
    vox291_36: THREE.Mesh
    vox291_37: THREE.Mesh
    vox291_38: THREE.Mesh
    vox291_39: THREE.Mesh
    vox379_1: THREE.Mesh
    vox379_2: THREE.Mesh
    vox379_3: THREE.Mesh
    vox379_4: THREE.Mesh
    vox379_5: THREE.Mesh
    vox379_6: THREE.Mesh
    vox379_7: THREE.Mesh
    vox379_8: THREE.Mesh
    vox702_1: THREE.Mesh
    vox702_2: THREE.Mesh
    vox702_3: THREE.Mesh
    vox702_4: THREE.Mesh
    vox702_5: THREE.Mesh
    vox702_6: THREE.Mesh
    vox702_7: THREE.Mesh
    vox702_8: THREE.Mesh
    vox702_9: THREE.Mesh
    vox702_10: THREE.Mesh
    vox702_11: THREE.Mesh
    vox702_12: THREE.Mesh
    vox702_13: THREE.Mesh
    vox702_14: THREE.Mesh
    vox702_15: THREE.Mesh
    vox702_16: THREE.Mesh
    vox702_17: THREE.Mesh
    vox702_18: THREE.Mesh
    vox702_19: THREE.Mesh
    vox702_20: THREE.Mesh
    vox703_1: THREE.Mesh
    vox703_2: THREE.Mesh
    vox703_3: THREE.Mesh
    vox703_4: THREE.Mesh
    vox703_5: THREE.Mesh
    vox703_6: THREE.Mesh
    vox703_7: THREE.Mesh
    vox703_8: THREE.Mesh
    vox703_9: THREE.Mesh
    vox703_10: THREE.Mesh
    vox703_11: THREE.Mesh
    vox703_12: THREE.Mesh
    vox703_13: THREE.Mesh
    vox703_14: THREE.Mesh
    vox703_15: THREE.Mesh
    vox703_16: THREE.Mesh
    vox703_17: THREE.Mesh
    vox703_18: THREE.Mesh
    vox704_1: THREE.Mesh
    vox704_2: THREE.Mesh
    vox704_3: THREE.Mesh
    vox704_4: THREE.Mesh
    vox705_1: THREE.Mesh
    vox705_2: THREE.Mesh
    vox705_3: THREE.Mesh
    vox705_4: THREE.Mesh
    vox705_5: THREE.Mesh
    vox705_6: THREE.Mesh
    vox705_7: THREE.Mesh
    vox705_8: THREE.Mesh
    vox705_9: THREE.Mesh
    vox705_10: THREE.Mesh
    vox705_11: THREE.Mesh
    vox705_12: THREE.Mesh
    vox705_13: THREE.Mesh
    vox705_14: THREE.Mesh
    vox705_15: THREE.Mesh
    vox705_16: THREE.Mesh
    vox705_17: THREE.Mesh
    vox705_18: THREE.Mesh
    vox705_19: THREE.Mesh
    vox705_20: THREE.Mesh
    vox705_21: THREE.Mesh
    vox705_22: THREE.Mesh
    vox706_1: THREE.Mesh
    vox706_2: THREE.Mesh
    vox706_3: THREE.Mesh
    vox706_4: THREE.Mesh
    vox706_5: THREE.Mesh
    vox706_6: THREE.Mesh
    vox706_7: THREE.Mesh
    vox706_8: THREE.Mesh
    vox706_9: THREE.Mesh
    vox706_10: THREE.Mesh
    vox706_11: THREE.Mesh
    vox706_12: THREE.Mesh
    vox706_13: THREE.Mesh
    vox706_14: THREE.Mesh
    vox706_15: THREE.Mesh
    vox706_16: THREE.Mesh
    vox706_17: THREE.Mesh
    vox706_18: THREE.Mesh
    vox706_19: THREE.Mesh
    vox706_20: THREE.Mesh
    vox706_21: THREE.Mesh
    vox706_22: THREE.Mesh
    vox740_1: THREE.Mesh
    vox740_2: THREE.Mesh
    vox740_3: THREE.Mesh
    vox740_4: THREE.Mesh
    vox740_5: THREE.Mesh
    vox740_6: THREE.Mesh
    vox740_7: THREE.Mesh
    vox740_8: THREE.Mesh
    vox740_9: THREE.Mesh
    vox740_10: THREE.Mesh
    vox740_11: THREE.Mesh
    vox740_12: THREE.Mesh
    vox740_13: THREE.Mesh
    vox740_14: THREE.Mesh
    vox741_1: THREE.Mesh
    vox741_2: THREE.Mesh
    vox741_3: THREE.Mesh
    vox741_4: THREE.Mesh
    vox741_5: THREE.Mesh
    vox741_6: THREE.Mesh
    vox741_7: THREE.Mesh
    vox741_8: THREE.Mesh
    vox741_9: THREE.Mesh
    vox741_10: THREE.Mesh
    vox741_11: THREE.Mesh
    vox741_12: THREE.Mesh
    vox741_13: THREE.Mesh
    vox741_14: THREE.Mesh
    vox742_1: THREE.Mesh
    vox742_2: THREE.Mesh
    vox742_3: THREE.Mesh
    vox742_4: THREE.Mesh
    vox742_5: THREE.Mesh
    vox742_6: THREE.Mesh
    vox742_7: THREE.Mesh
    vox742_8: THREE.Mesh
    vox742_9: THREE.Mesh
    vox742_10: THREE.Mesh
    vox742_11: THREE.Mesh
    vox742_12: THREE.Mesh
    vox742_13: THREE.Mesh
    vox742_14: THREE.Mesh
    vox742_15: THREE.Mesh
    vox742_16: THREE.Mesh
    vox742_17: THREE.Mesh
    vox742_18: THREE.Mesh
    vox742_19: THREE.Mesh
    vox742_20: THREE.Mesh
    vox742_21: THREE.Mesh
    vox744_1: THREE.Mesh
    vox744_2: THREE.Mesh
    vox744_3: THREE.Mesh
    vox744_4: THREE.Mesh
    vox744_5: THREE.Mesh
    vox745_1: THREE.Mesh
    vox745_2: THREE.Mesh
    vox745_3: THREE.Mesh
    vox745_4: THREE.Mesh
    vox745_5: THREE.Mesh
    vox746_1: THREE.Mesh
    vox746_2: THREE.Mesh
    vox746_3: THREE.Mesh
    vox746_4: THREE.Mesh
    vox746_5: THREE.Mesh
    vox747_1: THREE.Mesh
    vox747_2: THREE.Mesh
    vox747_3: THREE.Mesh
    vox747_4: THREE.Mesh
    vox747_5: THREE.Mesh
    vox748_1: THREE.Mesh
    vox748_2: THREE.Mesh
    vox748_3: THREE.Mesh
    vox748_4: THREE.Mesh
    vox748_5: THREE.Mesh
    vox749_1: THREE.Mesh
    vox749_2: THREE.Mesh
    vox749_3: THREE.Mesh
    vox749_4: THREE.Mesh
    vox749_5: THREE.Mesh
    vox750_1: THREE.Mesh
    vox750_2: THREE.Mesh
    vox750_3: THREE.Mesh
    vox750_4: THREE.Mesh
    vox750_5: THREE.Mesh
    vox751_1: THREE.Mesh
    vox751_2: THREE.Mesh
    vox751_3: THREE.Mesh
    vox751_4: THREE.Mesh
    vox752_1: THREE.Mesh
    vox752_2: THREE.Mesh
    vox752_3: THREE.Mesh
    vox752_4: THREE.Mesh
    vox753_1: THREE.Mesh
    vox753_2: THREE.Mesh
    vox753_3: THREE.Mesh
    vox753_4: THREE.Mesh
    vox754_1: THREE.Mesh
    vox754_2: THREE.Mesh
    vox754_3: THREE.Mesh
    vox754_4: THREE.Mesh
    vox755_1: THREE.Mesh
    vox755_2: THREE.Mesh
    vox755_3: THREE.Mesh
    vox755_4: THREE.Mesh
    vox755_5: THREE.Mesh
    vox755_6: THREE.Mesh
    vox755_7: THREE.Mesh
    vox756_1: THREE.Mesh
    vox756_2: THREE.Mesh
    vox756_3: THREE.Mesh
    vox756_4: THREE.Mesh
    vox756_5: THREE.Mesh
    vox756_6: THREE.Mesh
    vox756_7: THREE.Mesh
    vox802_1: THREE.Mesh
    vox802_2: THREE.Mesh
    vox802_3: THREE.Mesh
    vox802_4: THREE.Mesh
    vox802_5: THREE.Mesh
    vox803_1: THREE.Mesh
    vox803_2: THREE.Mesh
    vox803_3: THREE.Mesh
    vox803_4: THREE.Mesh
    vox803_5: THREE.Mesh
    vox803_6: THREE.Mesh
    vox803_7: THREE.Mesh
    vox803_8: THREE.Mesh
    vox803_9: THREE.Mesh
    vox803_10: THREE.Mesh
    vox803_11: THREE.Mesh
    vox803_12: THREE.Mesh
    vox803_13: THREE.Mesh
    vox803_14: THREE.Mesh
    vox803_15: THREE.Mesh
    vox803_16: THREE.Mesh
    vox803_17: THREE.Mesh
    vox803_18: THREE.Mesh
    vox803_19: THREE.Mesh
    vox803_20: THREE.Mesh
    templeCollider: THREE.Mesh
  }
  materials: {
    ['Material.010']: THREE.MeshPhysicalMaterial
    ['Material.011']: THREE.MeshPhysicalMaterial
    ['Material.012']: THREE.MeshPhysicalMaterial
    ['Material.013']: THREE.MeshPhysicalMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.120']: THREE.MeshPhysicalMaterial
    ['Material.128']: THREE.MeshPhysicalMaterial
    ['Material.136']: THREE.MeshPhysicalMaterial
    ['Material.144']: THREE.MeshPhysicalMaterial
    ['Material.216']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshPhysicalMaterial
    ['Material.112']: THREE.MeshPhysicalMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    ['Material.176']: THREE.MeshStandardMaterial
    ['Material.117']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshPhysicalMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.071']: THREE.MeshStandardMaterial
    ['Material.105']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
    ['Material.113']: THREE.MeshStandardMaterial
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.122']: THREE.MeshStandardMaterial
    ['Material.123']: THREE.MeshStandardMaterial
    ['Material.124']: THREE.MeshStandardMaterial
    ['Material.125']: THREE.MeshStandardMaterial
    ['Material.126']: THREE.MeshStandardMaterial
    ['Material.127']: THREE.MeshStandardMaterial
    ['Material.151']: THREE.MeshStandardMaterial
    ['Material.181']: THREE.MeshStandardMaterial
    ['Material.182']: THREE.MeshStandardMaterial
    ['Material.183']: THREE.MeshStandardMaterial
    ['Material.184']: THREE.MeshStandardMaterial
    ['Material.189']: THREE.MeshStandardMaterial
    ['Material.190']: THREE.MeshStandardMaterial
    ['Material.192']: THREE.MeshStandardMaterial
    ['Material.202']: THREE.MeshStandardMaterial
    ['Material.205']: THREE.MeshStandardMaterial
    ['Material.206']: THREE.MeshStandardMaterial
    ['Material.207']: THREE.MeshStandardMaterial
    ['Material.208']: THREE.MeshPhysicalMaterial
    ['Material.210']: THREE.MeshStandardMaterial
    ['Material.223']: THREE.MeshStandardMaterial
    ['Material.238']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshPhysicalMaterial
    ['Material.114']: THREE.MeshStandardMaterial
    ['Material.115']: THREE.MeshStandardMaterial
    ['Material.085']: THREE.MeshStandardMaterial
    ['Material.087']: THREE.MeshStandardMaterial
    ['Material.188']: THREE.MeshStandardMaterial
    ['Material.191']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.064']: THREE.MeshStandardMaterial
    ['Material.116']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.138']: THREE.MeshStandardMaterial
    ['Material.141']: THREE.MeshStandardMaterial
    ['Material.147']: THREE.MeshStandardMaterial
    ['Material.157']: THREE.MeshStandardMaterial
    ['Material.152']: THREE.MeshStandardMaterial
    ['Material.156']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.065']: THREE.MeshStandardMaterial
    ['Material.142']: THREE.MeshStandardMaterial
    ['Material.158']: THREE.MeshStandardMaterial
    ['Material.244']: THREE.MeshPhysicalMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.154']: THREE.MeshStandardMaterial
    ['Material.180']: THREE.MeshPhysicalMaterial
  }
}

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/temple10-1651539961/temple10.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult

  useTrimeshCollision((nodes["templeCollider"].geometry as BufferGeometry).clone()
    .scale(2.2784, 5.7516, 0.0053)
    .rotateX(-1.5703)
    .rotateY(-1.5708)
    .rotateZ(-0.0057)
    .translate(9.2409, 2.2881, 28.1735)
    .scale(1.25, 1.25, 1.25)
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Transform002" position={[9.8899, 8.9324, 3.979]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.1319}>
          <group name="Shape001">
            <group name="vox001">
              <mesh name="vox001_1" geometry={nodes.vox001_1.geometry} material={nodes.vox001_1.material} />
              <mesh name="vox001_2" geometry={nodes.vox001_2.geometry} material={nodes.vox001_2.material} />
              <mesh name="vox001_3" geometry={nodes.vox001_3.geometry} material={nodes.vox001_3.material} />
              <mesh name="vox001_4" geometry={nodes.vox001_4.geometry} material={nodes.vox001_4.material} />
              <mesh name="vox001_5" geometry={nodes.vox001_5.geometry} material={nodes.vox001_5.material} />
              <mesh name="vox001_6" geometry={nodes.vox001_6.geometry} material={nodes.vox001_6.material} />
              <mesh name="vox001_7" geometry={nodes.vox001_7.geometry} material={nodes.vox001_7.material} />
              <mesh name="vox001_8" geometry={nodes.vox001_8.geometry} material={nodes.vox001_8.material} />
              <mesh name="vox001_9" geometry={nodes.vox001_9.geometry} material={nodes.vox001_9.material} />
              <mesh name="vox001_10" geometry={nodes.vox001_10.geometry} material={nodes.vox001_10.material} />
              <mesh name="vox001_11" geometry={nodes.vox001_11.geometry} material={nodes.vox001_11.material} />
              <mesh name="vox001_12" geometry={nodes.vox001_12.geometry} material={nodes.vox001_12.material} />
              <mesh name="vox001_13" geometry={nodes.vox001_13.geometry} material={nodes.vox001_13.material} />
              <mesh name="vox001_14" geometry={nodes.vox001_14.geometry} material={nodes.vox001_14.material} />
              <mesh name="vox001_15" geometry={nodes.vox001_15.geometry} material={nodes.vox001_15.material} />
              <mesh name="vox001_16" geometry={nodes.vox001_16.geometry} material={nodes.vox001_16.material} />
              <mesh name="vox001_17" geometry={nodes.vox001_17.geometry} material={nodes.vox001_17.material} />
            </group>
          </group>
        </group>
        <group name="Transform003" position={[-6.3349, 10.1196, 10.1787]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape002">
            <group name="vox002">
              <mesh name="vox002_1" geometry={nodes.vox002_1.geometry} material={nodes.vox002_1.material} />
              <mesh name="vox002_2" geometry={nodes.vox002_2.geometry} material={nodes.vox002_2.material} />
              <mesh name="vox002_3" geometry={nodes.vox002_3.geometry} material={nodes.vox002_3.material} />
              <mesh name="vox002_4" geometry={nodes.vox002_4.geometry} material={nodes.vox002_4.material} />
              <mesh name="vox002_5" geometry={nodes.vox002_5.geometry} material={nodes.vox002_5.material} />
              <mesh name="vox002_6" geometry={nodes.vox002_6.geometry} material={nodes.vox002_6.material} />
              <mesh name="vox002_7" geometry={nodes.vox002_7.geometry} material={nodes.vox002_7.material} />
              <mesh name="vox002_8" geometry={nodes.vox002_8.geometry} material={nodes.vox002_8.material} />
              <mesh name="vox002_9" geometry={nodes.vox002_9.geometry} material={nodes.vox002_9.material} />
              <mesh name="vox002_10" geometry={nodes.vox002_10.geometry} material={nodes.vox002_10.material} />
              <mesh name="vox002_11" geometry={nodes.vox002_11.geometry} material={nodes.vox002_11.material} />
              <mesh name="vox002_12" geometry={nodes.vox002_12.geometry} material={nodes.vox002_12.material} />
              <mesh name="vox002_13" geometry={nodes.vox002_13.geometry} material={nodes.vox002_13.material} />
              <mesh name="vox002_14" geometry={nodes.vox002_14.geometry} material={nodes.vox002_14.material} />
              <mesh name="vox002_15" geometry={nodes.vox002_15.geometry} material={nodes.vox002_15.material} />
              <mesh name="vox002_16" geometry={nodes.vox002_16.geometry} material={nodes.vox002_16.material} />
              <mesh name="vox002_17" geometry={nodes.vox002_17.geometry} material={nodes.vox002_17.material} />
              <mesh name="vox002_18" geometry={nodes.vox002_18.geometry} material={nodes.vox002_18.material} />
            </group>
          </group>
        </group>
        <group name="Transform004" position={[-16.4918, 10.2515, 0.8132]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape003">
            <group name="vox003" position={[0, 0, 28.6194]}>
              <mesh name="vox003_1" geometry={nodes.vox003_1.geometry} material={nodes.vox003_1.material} />
              <mesh name="vox003_2" geometry={nodes.vox003_2.geometry} material={nodes.vox003_2.material} />
              <mesh name="vox003_3" geometry={nodes.vox003_3.geometry} material={nodes.vox003_3.material} />
            </group>
          </group>
        </group>
        <group
          name="Transform005"
          position={[6.7241, 10.1196, -7.1014]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.1319}>
          <group name="Shape004">
            <group name="vox004">
              <mesh name="vox004_1" geometry={nodes.vox004_1.geometry} material={nodes.vox004_1.material} />
              <mesh name="vox004_2" geometry={nodes.vox004_2.geometry} material={nodes.vox004_2.material} />
              <mesh name="vox004_3" geometry={nodes.vox004_3.geometry} material={nodes.vox004_3.material} />
              <mesh name="vox004_4" geometry={nodes.vox004_4.geometry} material={nodes.vox004_4.material} />
              <mesh name="vox004_5" geometry={nodes.vox004_5.geometry} material={nodes.vox004_5.material} />
              <mesh name="vox004_6" geometry={nodes.vox004_6.geometry} material={nodes.vox004_6.material} />
              <mesh name="vox004_7" geometry={nodes.vox004_7.geometry} material={nodes.vox004_7.material} />
              <mesh name="vox004_8" geometry={nodes.vox004_8.geometry} material={nodes.vox004_8.material} />
              <mesh name="vox004_9" geometry={nodes.vox004_9.geometry} material={nodes.vox004_9.material} />
              <mesh name="vox004_10" geometry={nodes.vox004_10.geometry} material={nodes.vox004_10.material} />
              <mesh name="vox004_11" geometry={nodes.vox004_11.geometry} material={nodes.vox004_11.material} />
              <mesh name="vox004_12" geometry={nodes.vox004_12.geometry} material={nodes.vox004_12.material} />
              <mesh name="vox004_13" geometry={nodes.vox004_13.geometry} material={nodes.vox004_13.material} />
              <mesh name="vox004_14" geometry={nodes.vox004_14.geometry} material={nodes.vox004_14.material} />
              <mesh name="vox004_15" geometry={nodes.vox004_15.geometry} material={nodes.vox004_15.material} />
              <mesh name="vox004_16" geometry={nodes.vox004_16.geometry} material={nodes.vox004_16.material} />
            </group>
          </group>
        </group>
        <group
          name="Transform006"
          position={[-10.2921, 10.3834, -7.1014]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.1319}>
          <group name="Shape005">
            <group name="vox005">
              <mesh name="vox005_1" geometry={nodes.vox005_1.geometry} material={nodes.vox005_1.material} />
              <mesh name="vox005_2" geometry={nodes.vox005_2.geometry} material={nodes.vox005_2.material} />
              <mesh name="vox005_3" geometry={nodes.vox005_3.geometry} material={nodes.vox005_3.material} />
            </group>
          </group>
        </group>
        <group name="Transform121" position={[32.1825, 0.886, 17.8294]} scale={0.1319}>
          <group name="Shape120">
            <group name="vox120">
              <mesh name="vox120_1" geometry={nodes.vox120_1.geometry} material={nodes.vox120_1.material} />
              <mesh name="vox120_2" geometry={nodes.vox120_2.geometry} material={nodes.vox120_2.material} />
              <mesh name="vox120_3" geometry={nodes.vox120_3.geometry} material={nodes.vox120_3.material} />
              <mesh name="vox120_4" geometry={nodes.vox120_4.geometry} material={nodes.vox120_4.material} />
              <mesh name="vox120_5" geometry={nodes.vox120_5.geometry} material={nodes.vox120_5.material} />
              <mesh name="vox120_6" geometry={nodes.vox120_6.geometry} material={materials['Material.117']} />
            </group>
          </group>
        </group>
        <group name="Transform122" position={[-36.6739, 7.2176, -2.0888]} scale={0.1319}>
          <group name="Shape121">
            <group name="vox121">
              <mesh name="vox121_1" geometry={nodes.vox121_1.geometry} material={nodes.vox121_1.material} />
              <mesh name="vox121_2" geometry={nodes.vox121_2.geometry} material={nodes.vox121_2.material} />
              <mesh name="vox121_3" geometry={nodes.vox121_3.geometry} material={nodes.vox121_3.material} />
              <mesh name="vox121_4" geometry={nodes.vox121_4.geometry} material={nodes.vox121_4.material} />
              <mesh name="vox121_5" geometry={nodes.vox121_5.geometry} material={nodes.vox121_5.material} />
              <mesh name="vox121_6" geometry={nodes.vox121_6.geometry} material={nodes.vox121_6.material} />
              <mesh name="vox121_7" geometry={nodes.vox121_7.geometry} material={nodes.vox121_7.material} />
              <mesh name="vox121_8" geometry={nodes.vox121_8.geometry} material={nodes.vox121_8.material} />
              <mesh name="vox121_9" geometry={nodes.vox121_9.geometry} material={nodes.vox121_9.material} />
              <mesh name="vox121_10" geometry={nodes.vox121_10.geometry} material={nodes.vox121_10.material} />
              <mesh name="vox121_11" geometry={nodes.vox121_11.geometry} material={nodes.vox121_11.material} />
              <mesh name="vox121_12" geometry={nodes.vox121_12.geometry} material={nodes.vox121_12.material} />
              <mesh name="vox121_13" geometry={nodes.vox121_13.geometry} material={nodes.vox121_13.material} />
            </group>
          </group>
        </group>
        <group name="Transform292" position={[0.1287, 26.0805, 0.1536]} scale={0.1319}>
          <group name="Shape291">
            <group name="vox291">
              <mesh name="vox291_1" geometry={nodes.vox291_1.geometry} material={nodes.vox291_1.material} />
              <mesh name="vox291_2" geometry={nodes.vox291_2.geometry} material={materials['Material.028']} />
              <mesh name="vox291_3" geometry={nodes.vox291_3.geometry} material={materials['Material.029']} />
              <mesh name="vox291_4" geometry={nodes.vox291_4.geometry} material={nodes.vox291_4.material} />
              <mesh name="vox291_5" geometry={nodes.vox291_5.geometry} material={nodes.vox291_5.material} />
              <mesh name="vox291_6" geometry={nodes.vox291_6.geometry} material={nodes.vox291_6.material} />
              <mesh name="vox291_7" geometry={nodes.vox291_7.geometry} material={materials['Material.044']} />
              <mesh name="vox291_8" geometry={nodes.vox291_8.geometry} material={nodes.vox291_8.material} />
              <mesh name="vox291_9" geometry={nodes.vox291_9.geometry} material={nodes.vox291_9.material} />
              <mesh name="vox291_10" geometry={nodes.vox291_10.geometry} material={nodes.vox291_10.material} />
              <mesh name="vox291_11" geometry={nodes.vox291_11.geometry} material={nodes.vox291_11.material} />
              <mesh name="vox291_12" geometry={nodes.vox291_12.geometry} material={nodes.vox291_12.material} />
              <mesh name="vox291_13" geometry={nodes.vox291_13.geometry} material={nodes.vox291_13.material} />
              <mesh name="vox291_14" geometry={nodes.vox291_14.geometry} material={materials['Material.108']} />
              <mesh name="vox291_15" geometry={nodes.vox291_15.geometry} material={nodes.vox291_15.material} />
              <mesh name="vox291_16" geometry={nodes.vox291_16.geometry} material={materials['Material.121']} />
              <mesh name="vox291_17" geometry={nodes.vox291_17.geometry} material={nodes.vox291_17.material} />
              <mesh name="vox291_18" geometry={nodes.vox291_18.geometry} material={nodes.vox291_18.material} />
              <mesh name="vox291_19" geometry={nodes.vox291_19.geometry} material={materials['Material.124']} />
              <mesh name="vox291_20" geometry={nodes.vox291_20.geometry} material={nodes.vox291_20.material} />
              <mesh name="vox291_21" geometry={nodes.vox291_21.geometry} material={nodes.vox291_21.material} />
              <mesh name="vox291_22" geometry={nodes.vox291_22.geometry} material={materials['Material.127']} />
              <mesh name="vox291_23" geometry={nodes.vox291_23.geometry} material={materials['Material.151']} />
              <mesh name="vox291_24" geometry={nodes.vox291_24.geometry} material={nodes.vox291_24.material} />
              <mesh name="vox291_25" geometry={nodes.vox291_25.geometry} material={nodes.vox291_25.material} />
              <mesh name="vox291_26" geometry={nodes.vox291_26.geometry} material={nodes.vox291_26.material} />
              <mesh name="vox291_27" geometry={nodes.vox291_27.geometry} material={nodes.vox291_27.material} />
              <mesh name="vox291_28" geometry={nodes.vox291_28.geometry} material={nodes.vox291_28.material} />
              <mesh name="vox291_29" geometry={nodes.vox291_29.geometry} material={nodes.vox291_29.material} />
              <mesh name="vox291_30" geometry={nodes.vox291_30.geometry} material={nodes.vox291_30.material} />
              <mesh name="vox291_31" geometry={nodes.vox291_31.geometry} material={materials['Material.202']} />
              <mesh name="vox291_32" geometry={nodes.vox291_32.geometry} material={materials['Material.205']} />
              <mesh name="vox291_33" geometry={nodes.vox291_33.geometry} material={materials['Material.206']} />
              <mesh name="vox291_34" geometry={nodes.vox291_34.geometry} material={materials['Material.207']} />
              <mesh name="vox291_35" geometry={nodes.vox291_35.geometry} material={materials['Material.208']} />
              <mesh name="vox291_36" geometry={nodes.vox291_36.geometry} material={materials['Material.210']} />
              <mesh name="vox291_37" geometry={nodes.vox291_37.geometry} material={nodes.vox291_37.material} />
              <mesh name="vox291_38" geometry={nodes.vox291_38.geometry} material={nodes.vox291_38.material} />
              <mesh name="vox291_39" geometry={nodes.vox291_39.geometry} material={nodes.vox291_39.material} />
            </group>
          </group>
        </group>
        <group name="Transform380" position={[15.8258, 0.2264, 16.2465]} rotation={[0, -1.5705, 0]} scale={0.1319}>
          <group name="Shape379">
            <group name="vox379" position={[0, 0, -5.131]} rotation={[3.1404, 0, 0]}>
              <mesh name="vox379_1" geometry={nodes.vox379_1.geometry} material={nodes.vox379_1.material} />
              <mesh name="vox379_2" geometry={nodes.vox379_2.geometry} material={nodes.vox379_2.material} />
              <mesh name="vox379_3" geometry={nodes.vox379_3.geometry} material={nodes.vox379_3.material} />
              <mesh name="vox379_4" geometry={nodes.vox379_4.geometry} material={nodes.vox379_4.material} />
              <mesh name="vox379_5" geometry={nodes.vox379_5.geometry} material={nodes.vox379_5.material} />
              <mesh name="vox379_6" geometry={nodes.vox379_6.geometry} material={nodes.vox379_6.material} />
              <mesh name="vox379_7" geometry={nodes.vox379_7.geometry} material={nodes.vox379_7.material} />
              <mesh name="vox379_8" geometry={nodes.vox379_8.geometry} material={nodes.vox379_8.material} />
            </group>
          </group>
        </group>
        <group name="Transform703" position={[5.0093, 14.7364, 18.0932]} scale={0.1319}>
          <group name="Shape702">
            <group name="vox702">
              <mesh name="vox702_1" geometry={nodes.vox702_1.geometry} material={nodes.vox702_1.material} />
              <mesh name="vox702_2" geometry={nodes.vox702_2.geometry} material={nodes.vox702_2.material} />
              <mesh name="vox702_3" geometry={nodes.vox702_3.geometry} material={nodes.vox702_3.material} />
              <mesh name="vox702_4" geometry={nodes.vox702_4.geometry} material={nodes.vox702_4.material} />
              <mesh name="vox702_5" geometry={nodes.vox702_5.geometry} material={nodes.vox702_5.material} />
              <mesh name="vox702_6" geometry={nodes.vox702_6.geometry} material={nodes.vox702_6.material} />
              <mesh name="vox702_7" geometry={nodes.vox702_7.geometry} material={nodes.vox702_7.material} />
              <mesh name="vox702_8" geometry={nodes.vox702_8.geometry} material={nodes.vox702_8.material} />
              <mesh name="vox702_9" geometry={nodes.vox702_9.geometry} material={nodes.vox702_9.material} />
              <mesh name="vox702_10" geometry={nodes.vox702_10.geometry} material={nodes.vox702_10.material} />
              <mesh name="vox702_11" geometry={nodes.vox702_11.geometry} material={nodes.vox702_11.material} />
              <mesh name="vox702_12" geometry={nodes.vox702_12.geometry} material={nodes.vox702_12.material} />
              <mesh name="vox702_13" geometry={nodes.vox702_13.geometry} material={nodes.vox702_13.material} />
              <mesh name="vox702_14" geometry={nodes.vox702_14.geometry} material={nodes.vox702_14.material} />
              <mesh name="vox702_15" geometry={nodes.vox702_15.geometry} material={nodes.vox702_15.material} />
              <mesh name="vox702_16" geometry={nodes.vox702_16.geometry} material={nodes.vox702_16.material} />
              <mesh name="vox702_17" geometry={nodes.vox702_17.geometry} material={nodes.vox702_17.material} />
              <mesh name="vox702_18" geometry={nodes.vox702_18.geometry} material={nodes.vox702_18.material} />
              <mesh name="vox702_19" geometry={nodes.vox702_19.geometry} material={nodes.vox702_19.material} />
              <mesh name="vox702_20" geometry={nodes.vox702_20.geometry} material={nodes.vox702_20.material} />
            </group>
          </group>
        </group>
        <group name="Transform704" position={[-0.7947, 14.6045, 9.9149]} scale={0.1319}>
          <group name="Shape703">
            <group name="vox703">
              <mesh name="vox703_1" geometry={nodes.vox703_1.geometry} material={nodes.vox703_1.material} />
              <mesh name="vox703_2" geometry={nodes.vox703_2.geometry} material={nodes.vox703_2.material} />
              <mesh name="vox703_3" geometry={nodes.vox703_3.geometry} material={nodes.vox703_3.material} />
              <mesh name="vox703_4" geometry={nodes.vox703_4.geometry} material={nodes.vox703_4.material} />
              <mesh name="vox703_5" geometry={nodes.vox703_5.geometry} material={nodes.vox703_5.material} />
              <mesh name="vox703_6" geometry={nodes.vox703_6.geometry} material={nodes.vox703_6.material} />
              <mesh name="vox703_7" geometry={nodes.vox703_7.geometry} material={nodes.vox703_7.material} />
              <mesh name="vox703_8" geometry={nodes.vox703_8.geometry} material={nodes.vox703_8.material} />
              <mesh name="vox703_9" geometry={nodes.vox703_9.geometry} material={nodes.vox703_9.material} />
              <mesh name="vox703_10" geometry={nodes.vox703_10.geometry} material={nodes.vox703_10.material} />
              <mesh name="vox703_11" geometry={nodes.vox703_11.geometry} material={nodes.vox703_11.material} />
              <mesh name="vox703_12" geometry={nodes.vox703_12.geometry} material={materials['Material.110']} />
              <mesh name="vox703_13" geometry={nodes.vox703_13.geometry} material={nodes.vox703_13.material} />
              <mesh name="vox703_14" geometry={nodes.vox703_14.geometry} material={nodes.vox703_14.material} />
              <mesh name="vox703_15" geometry={nodes.vox703_15.geometry} material={nodes.vox703_15.material} />
              <mesh name="vox703_16" geometry={nodes.vox703_16.geometry} material={nodes.vox703_16.material} />
              <mesh name="vox703_17" geometry={nodes.vox703_17.geometry} material={nodes.vox703_17.material} />
              <mesh name="vox703_18" geometry={nodes.vox703_18.geometry} material={nodes.vox703_18.material} />
            </group>
          </group>
        </group>
        <group name="Transform705" position={[-0.0032, 41.1181, -2.2207]} scale={0.1319}>
          <group name="Shape704">
            <group name="vox704">
              <mesh name="vox704_1" geometry={nodes.vox704_1.geometry} material={nodes.vox704_1.material} />
              <mesh name="vox704_2" geometry={nodes.vox704_2.geometry} material={nodes.vox704_2.material} />
              <mesh name="vox704_3" geometry={nodes.vox704_3.geometry} material={nodes.vox704_3.material} />
              <mesh name="vox704_4" geometry={nodes.vox704_4.geometry} material={nodes.vox704_4.material} />
            </group>
          </group>
        </group>
        <group name="Transform706" position={[11.209, 8.009, 11.2339]} scale={0.1319}>
          <group name="Shape705">
            <group name="vox705">
              <mesh name="vox705_1" geometry={nodes.vox705_1.geometry} material={nodes.vox705_1.material} />
              <mesh name="vox705_2" geometry={nodes.vox705_2.geometry} material={nodes.vox705_2.material} />
              <mesh name="vox705_3" geometry={nodes.vox705_3.geometry} material={nodes.vox705_3.material} />
              <mesh name="vox705_4" geometry={nodes.vox705_4.geometry} material={nodes.vox705_4.material} />
              <mesh name="vox705_5" geometry={nodes.vox705_5.geometry} material={nodes.vox705_5.material} />
              <mesh name="vox705_6" geometry={nodes.vox705_6.geometry} material={nodes.vox705_6.material} />
              <mesh name="vox705_7" geometry={nodes.vox705_7.geometry} material={nodes.vox705_7.material} />
              <mesh name="vox705_8" geometry={nodes.vox705_8.geometry} material={nodes.vox705_8.material} />
              <mesh name="vox705_9" geometry={nodes.vox705_9.geometry} material={nodes.vox705_9.material} />
              <mesh name="vox705_10" geometry={nodes.vox705_10.geometry} material={nodes.vox705_10.material} />
              <mesh name="vox705_11" geometry={nodes.vox705_11.geometry} material={nodes.vox705_11.material} />
              <mesh name="vox705_12" geometry={nodes.vox705_12.geometry} material={nodes.vox705_12.material} />
              <mesh name="vox705_13" geometry={nodes.vox705_13.geometry} material={nodes.vox705_13.material} />
              <mesh name="vox705_14" geometry={nodes.vox705_14.geometry} material={nodes.vox705_14.material} />
              <mesh name="vox705_15" geometry={nodes.vox705_15.geometry} material={nodes.vox705_15.material} />
              <mesh name="vox705_16" geometry={nodes.vox705_16.geometry} material={nodes.vox705_16.material} />
              <mesh name="vox705_17" geometry={nodes.vox705_17.geometry} material={nodes.vox705_17.material} />
              <mesh name="vox705_18" geometry={nodes.vox705_18.geometry} material={nodes.vox705_18.material} />
              <mesh name="vox705_19" geometry={nodes.vox705_19.geometry} material={nodes.vox705_19.material} />
              <mesh name="vox705_20" geometry={nodes.vox705_20.geometry} material={nodes.vox705_20.material} />
              <mesh name="vox705_21" geometry={nodes.vox705_21.geometry} material={nodes.vox705_21.material} />
              <mesh name="vox705_22" geometry={nodes.vox705_22.geometry} material={nodes.vox705_22.material} />
            </group>
          </group>
        </group>
        <group name="Transform707" position={[5.405, 5.8985, 14.2678]} scale={0.1319}>
          <group name="Shape706">
            <group name="vox706">
              <mesh name="vox706_1" geometry={nodes.vox706_1.geometry} material={nodes.vox706_1.material} />
              <mesh name="vox706_2" geometry={nodes.vox706_2.geometry} material={nodes.vox706_2.material} />
              <mesh name="vox706_3" geometry={nodes.vox706_3.geometry} material={nodes.vox706_3.material} />
              <mesh name="vox706_4" geometry={nodes.vox706_4.geometry} material={nodes.vox706_4.material} />
              <mesh name="vox706_5" geometry={nodes.vox706_5.geometry} material={nodes.vox706_5.material} />
              <mesh name="vox706_6" geometry={nodes.vox706_6.geometry} material={nodes.vox706_6.material} />
              <mesh name="vox706_7" geometry={nodes.vox706_7.geometry} material={nodes.vox706_7.material} />
              <mesh name="vox706_8" geometry={nodes.vox706_8.geometry} material={nodes.vox706_8.material} />
              <mesh name="vox706_9" geometry={nodes.vox706_9.geometry} material={nodes.vox706_9.material} />
              <mesh name="vox706_10" geometry={nodes.vox706_10.geometry} material={nodes.vox706_10.material} />
              <mesh name="vox706_11" geometry={nodes.vox706_11.geometry} material={nodes.vox706_11.material} />
              <mesh name="vox706_12" geometry={nodes.vox706_12.geometry} material={nodes.vox706_12.material} />
              <mesh name="vox706_13" geometry={nodes.vox706_13.geometry} material={nodes.vox706_13.material} />
              <mesh name="vox706_14" geometry={nodes.vox706_14.geometry} material={nodes.vox706_14.material} />
              <mesh name="vox706_15" geometry={nodes.vox706_15.geometry} material={nodes.vox706_15.material} />
              <mesh name="vox706_16" geometry={nodes.vox706_16.geometry} material={nodes.vox706_16.material} />
              <mesh name="vox706_17" geometry={nodes.vox706_17.geometry} material={nodes.vox706_17.material} />
              <mesh name="vox706_18" geometry={nodes.vox706_18.geometry} material={nodes.vox706_18.material} />
              <mesh name="vox706_19" geometry={nodes.vox706_19.geometry} material={nodes.vox706_19.material} />
              <mesh name="vox706_20" geometry={nodes.vox706_20.geometry} material={nodes.vox706_20.material} />
              <mesh name="vox706_21" geometry={nodes.vox706_21.geometry} material={nodes.vox706_21.material} />
              <mesh name="vox706_22" geometry={nodes.vox706_22.geometry} material={nodes.vox706_22.material} />
            </group>
          </group>
        </group>
        <group name="Transform741" position={[1.052, 19.0894, -2.4846]} scale={0.1319}>
          <group name="Shape740">
            <group name="vox740">
              <mesh name="vox740_1" geometry={nodes.vox740_1.geometry} material={nodes.vox740_1.material} />
              <mesh name="vox740_2" geometry={nodes.vox740_2.geometry} material={nodes.vox740_2.material} />
              <mesh name="vox740_3" geometry={nodes.vox740_3.geometry} material={nodes.vox740_3.material} />
              <mesh name="vox740_4" geometry={nodes.vox740_4.geometry} material={nodes.vox740_4.material} />
              <mesh name="vox740_5" geometry={nodes.vox740_5.geometry} material={nodes.vox740_5.material} />
              <mesh name="vox740_6" geometry={nodes.vox740_6.geometry} material={nodes.vox740_6.material} />
              <mesh name="vox740_7" geometry={nodes.vox740_7.geometry} material={nodes.vox740_7.material} />
              <mesh name="vox740_8" geometry={nodes.vox740_8.geometry} material={nodes.vox740_8.material} />
              <mesh name="vox740_9" geometry={nodes.vox740_9.geometry} material={nodes.vox740_9.material} />
              <mesh name="vox740_10" geometry={nodes.vox740_10.geometry} material={nodes.vox740_10.material} />
              <mesh name="vox740_11" geometry={nodes.vox740_11.geometry} material={nodes.vox740_11.material} />
              <mesh name="vox740_12" geometry={nodes.vox740_12.geometry} material={nodes.vox740_12.material} />
              <mesh name="vox740_13" geometry={nodes.vox740_13.geometry} material={nodes.vox740_13.material} />
              <mesh name="vox740_14" geometry={nodes.vox740_14.geometry} material={nodes.vox740_14.material} />
            </group>
          </group>
        </group>
        <group name="Transform742" position={[0.3925, 13.0216, -1.1655]} scale={0.1319}>
          <group name="Shape741">
            <group name="vox741" position={[0, 0.8605, -11.0072]}>
              <mesh name="vox741_1" geometry={nodes.vox741_1.geometry} material={nodes.vox741_1.material} />
              <mesh name="vox741_2" geometry={nodes.vox741_2.geometry} material={nodes.vox741_2.material} />
              <mesh name="vox741_3" geometry={nodes.vox741_3.geometry} material={nodes.vox741_3.material} />
              <mesh name="vox741_4" geometry={nodes.vox741_4.geometry} material={nodes.vox741_4.material} />
              <mesh name="vox741_5" geometry={nodes.vox741_5.geometry} material={nodes.vox741_5.material} />
              <mesh name="vox741_6" geometry={nodes.vox741_6.geometry} material={nodes.vox741_6.material} />
              <mesh name="vox741_7" geometry={nodes.vox741_7.geometry} material={nodes.vox741_7.material} />
              <mesh name="vox741_8" geometry={nodes.vox741_8.geometry} material={nodes.vox741_8.material} />
              <mesh name="vox741_9" geometry={nodes.vox741_9.geometry} material={nodes.vox741_9.material} />
              <mesh name="vox741_10" geometry={nodes.vox741_10.geometry} material={nodes.vox741_10.material} />
              <mesh name="vox741_11" geometry={nodes.vox741_11.geometry} material={nodes.vox741_11.material} />
              <mesh name="vox741_12" geometry={nodes.vox741_12.geometry} material={nodes.vox741_12.material} />
              <mesh name="vox741_13" geometry={nodes.vox741_13.geometry} material={nodes.vox741_13.material} />
              <mesh name="vox741_14" geometry={nodes.vox741_14.geometry} material={nodes.vox741_14.material} />
            </group>
          </group>
        </group>
        <group name="Transform743" position={[19.2554, 7.0857, -64.4817]} scale={0.1319}>
          <group name="Shape742">
            <group name="vox742">
              <mesh name="vox742_1" geometry={nodes.vox742_1.geometry} material={nodes.vox742_1.material} />
              <mesh name="vox742_2" geometry={nodes.vox742_2.geometry} material={nodes.vox742_2.material} />
              <mesh name="vox742_3" geometry={nodes.vox742_3.geometry} material={nodes.vox742_3.material} />
              <mesh name="vox742_4" geometry={nodes.vox742_4.geometry} material={nodes.vox742_4.material} />
              <mesh name="vox742_5" geometry={nodes.vox742_5.geometry} material={nodes.vox742_5.material} />
              <mesh name="vox742_6" geometry={nodes.vox742_6.geometry} material={nodes.vox742_6.material} />
              <mesh name="vox742_7" geometry={nodes.vox742_7.geometry} material={nodes.vox742_7.material} />
              <mesh name="vox742_8" geometry={nodes.vox742_8.geometry} material={nodes.vox742_8.material} />
              <mesh name="vox742_9" geometry={nodes.vox742_9.geometry} material={nodes.vox742_9.material} />
              <mesh name="vox742_10" geometry={nodes.vox742_10.geometry} material={nodes.vox742_10.material} />
              <mesh name="vox742_11" geometry={nodes.vox742_11.geometry} material={nodes.vox742_11.material} />
              <mesh name="vox742_12" geometry={nodes.vox742_12.geometry} material={materials['Material.054']} />
              <mesh name="vox742_13" geometry={nodes.vox742_13.geometry} material={nodes.vox742_13.material} />
              <mesh name="vox742_14" geometry={nodes.vox742_14.geometry} material={materials['Material.065']} />
              <mesh name="vox742_15" geometry={nodes.vox742_15.geometry} material={nodes.vox742_15.material} />
              <mesh name="vox742_16" geometry={nodes.vox742_16.geometry} material={nodes.vox742_16.material} />
              <mesh name="vox742_17" geometry={nodes.vox742_17.geometry} material={materials['Material.142']} />
              <mesh name="vox742_18" geometry={nodes.vox742_18.geometry} material={nodes.vox742_18.material} />
              <mesh name="vox742_19" geometry={nodes.vox742_19.geometry} material={materials['Material.158']} />
              <mesh name="vox742_20" geometry={nodes.vox742_20.geometry} material={nodes.vox742_20.material} />
              <mesh name="vox742_21" geometry={nodes.vox742_21.geometry} material={materials['Material.244']} />
            </group>
          </group>
        </group>
        <group name="Transform745" position={[-3.4329, 13.9449, 5.0342]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape744">
            <group name="vox744">
              <mesh name="vox744_1" geometry={nodes.vox744_1.geometry} material={nodes.vox744_1.material} />
              <mesh name="vox744_2" geometry={nodes.vox744_2.geometry} material={nodes.vox744_2.material} />
              <mesh name="vox744_3" geometry={nodes.vox744_3.geometry} material={nodes.vox744_3.material} />
              <mesh name="vox744_4" geometry={nodes.vox744_4.geometry} material={nodes.vox744_4.material} />
              <mesh name="vox744_5" geometry={nodes.vox744_5.geometry} material={nodes.vox744_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform746" position={[2.3711, 13.9449, 4.9023]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape745">
            <group name="vox745">
              <mesh name="vox745_1" geometry={nodes.vox745_1.geometry} material={nodes.vox745_1.material} />
              <mesh name="vox745_2" geometry={nodes.vox745_2.geometry} material={nodes.vox745_2.material} />
              <mesh name="vox745_3" geometry={nodes.vox745_3.geometry} material={nodes.vox745_3.material} />
              <mesh name="vox745_4" geometry={nodes.vox745_4.geometry} material={nodes.vox745_4.material} />
              <mesh name="vox745_5" geometry={nodes.vox745_5.geometry} material={nodes.vox745_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform747" position={[-0.6628, 20.0127, 4.9023]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape746">
            <group name="vox746">
              <mesh name="vox746_1" geometry={nodes.vox746_1.geometry} material={nodes.vox746_1.material} />
              <mesh name="vox746_2" geometry={nodes.vox746_2.geometry} material={nodes.vox746_2.material} />
              <mesh name="vox746_3" geometry={nodes.vox746_3.geometry} material={nodes.vox746_3.material} />
              <mesh name="vox746_4" geometry={nodes.vox746_4.geometry} material={nodes.vox746_4.material} />
              <mesh name="vox746_5" geometry={nodes.vox746_5.geometry} material={nodes.vox746_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform748" position={[-0.6628, 33.8631, 1.077]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape747">
            <group name="vox747">
              <mesh name="vox747_1" geometry={nodes.vox747_1.geometry} material={nodes.vox747_1.material} />
              <mesh name="vox747_2" geometry={nodes.vox747_2.geometry} material={nodes.vox747_2.material} />
              <mesh name="vox747_3" geometry={nodes.vox747_3.geometry} material={nodes.vox747_3.material} />
              <mesh name="vox747_4" geometry={nodes.vox747_4.geometry} material={nodes.vox747_4.material} />
              <mesh name="vox747_5" geometry={nodes.vox747_5.geometry} material={nodes.vox747_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform749" position={[-0.6628, 28.0592, 3.3194]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape748">
            <group name="vox748">
              <mesh name="vox748_1" geometry={nodes.vox748_1.geometry} material={nodes.vox748_1.material} />
              <mesh name="vox748_2" geometry={nodes.vox748_2.geometry} material={nodes.vox748_2.material} />
              <mesh name="vox748_3" geometry={nodes.vox748_3.geometry} material={nodes.vox748_3.material} />
              <mesh name="vox748_4" geometry={nodes.vox748_4.geometry} material={nodes.vox748_4.material} />
              <mesh name="vox748_5" geometry={nodes.vox748_5.geometry} material={nodes.vox748_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform750" position={[4.6136, 11.8344, 10.1787]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape749">
            <group name="vox749">
              <mesh name="vox749_1" geometry={nodes.vox749_1.geometry} material={nodes.vox749_1.material} />
              <mesh name="vox749_2" geometry={nodes.vox749_2.geometry} material={nodes.vox749_2.material} />
              <mesh name="vox749_3" geometry={nodes.vox749_3.geometry} material={nodes.vox749_3.material} />
              <mesh name="vox749_4" geometry={nodes.vox749_4.geometry} material={nodes.vox749_4.material} />
              <mesh name="vox749_5" geometry={nodes.vox749_5.geometry} material={nodes.vox749_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform751" position={[-5.0158, 11.8344, 10.1787]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape750">
            <group name="vox750">
              <mesh name="vox750_1" geometry={nodes.vox750_1.geometry} material={nodes.vox750_1.material} />
              <mesh name="vox750_2" geometry={nodes.vox750_2.geometry} material={nodes.vox750_2.material} />
              <mesh name="vox750_3" geometry={nodes.vox750_3.geometry} material={nodes.vox750_3.material} />
              <mesh name="vox750_4" geometry={nodes.vox750_4.geometry} material={nodes.vox750_4.material} />
              <mesh name="vox750_5" geometry={nodes.vox750_5.geometry} material={nodes.vox750_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform752" position={[-4.4881, 12.362, 9.3872]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape751">
            <group name="vox751">
              <mesh name="vox751_1" geometry={nodes.vox751_1.geometry} material={nodes.vox751_1.material} />
              <mesh name="vox751_2" geometry={nodes.vox751_2.geometry} material={nodes.vox751_2.material} />
              <mesh name="vox751_3" geometry={nodes.vox751_3.geometry} material={nodes.vox751_3.material} />
              <mesh name="vox751_4" geometry={nodes.vox751_4.geometry} material={nodes.vox751_4.material} />
            </group>
          </group>
        </group>
        <group name="Transform753" position={[5.405, 12.362, 9.3872]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape752">
            <group name="vox752">
              <mesh name="vox752_1" geometry={nodes.vox752_1.geometry} material={nodes.vox752_1.material} />
              <mesh name="vox752_2" geometry={nodes.vox752_2.geometry} material={nodes.vox752_2.material} />
              <mesh name="vox752_3" geometry={nodes.vox752_3.geometry} material={nodes.vox752_3.material} />
              <mesh name="vox752_4" geometry={nodes.vox752_4.geometry} material={nodes.vox752_4.material} />
            </group>
          </group>
        </group>
        <group name="Transform754" position={[5.6688, 8.009, 14.9274]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape753">
            <group name="vox753">
              <mesh name="vox753_1" geometry={nodes.vox753_1.geometry} material={nodes.vox753_1.material} />
              <mesh name="vox753_2" geometry={nodes.vox753_2.geometry} material={nodes.vox753_2.material} />
              <mesh name="vox753_3" geometry={nodes.vox753_3.geometry} material={nodes.vox753_3.material} />
              <mesh name="vox753_4" geometry={nodes.vox753_4.geometry} material={nodes.vox753_4.material} />
            </group>
          </group>
        </group>
        <group name="Transform755" position={[11.4728, 8.009, 14.9274]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape754">
            <group name="vox754">
              <mesh name="vox754_1" geometry={nodes.vox754_1.geometry} material={nodes.vox754_1.material} />
              <mesh name="vox754_2" geometry={nodes.vox754_2.geometry} material={nodes.vox754_2.material} />
              <mesh name="vox754_3" geometry={nodes.vox754_3.geometry} material={nodes.vox754_3.material} />
              <mesh name="vox754_4" geometry={nodes.vox754_4.geometry} material={nodes.vox754_4.material} />
            </group>
          </group>
        </group>
        <group name="Transform756" position={[18.2002, 0.2264, -18.8412]} rotation={[0, 1.5705, 0]} scale={0.1319}>
          <group name="Shape755">
            <group name="vox755" position={[56.9677, 0, -12.0683]}>
              <mesh name="vox755_1" geometry={nodes.vox755_1.geometry} material={nodes.vox755_1.material} />
              <mesh name="vox755_2" geometry={nodes.vox755_2.geometry} material={nodes.vox755_2.material} />
              <mesh name="vox755_3" geometry={nodes.vox755_3.geometry} material={nodes.vox755_3.material} />
              <mesh name="vox755_4" geometry={nodes.vox755_4.geometry} material={nodes.vox755_4.material} />
              <mesh name="vox755_5" geometry={nodes.vox755_5.geometry} material={nodes.vox755_5.material} />
              <mesh name="vox755_6" geometry={nodes.vox755_6.geometry} material={nodes.vox755_6.material} />
              <mesh name="vox755_7" geometry={nodes.vox755_7.geometry} material={nodes.vox755_7.material} />
            </group>
          </group>
        </group>
        <group
          name="Transform757"
          position={[18.7278, 0.0945, -71.6047]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.1319}>
          <group name="Shape756">
            <group name="vox756">
              <mesh name="vox756_1" geometry={nodes.vox756_1.geometry} material={nodes.vox756_1.material} />
              <mesh name="vox756_2" geometry={nodes.vox756_2.geometry} material={nodes.vox756_2.material} />
              <mesh name="vox756_3" geometry={nodes.vox756_3.geometry} material={nodes.vox756_3.material} />
              <mesh name="vox756_4" geometry={nodes.vox756_4.geometry} material={nodes.vox756_4.material} />
              <mesh name="vox756_5" geometry={nodes.vox756_5.geometry} material={nodes.vox756_5.material} />
              <mesh name="vox756_6" geometry={nodes.vox756_6.geometry} material={nodes.vox756_6.material} />
              <mesh name="vox756_7" geometry={nodes.vox756_7.geometry} material={nodes.vox756_7.material} />
            </group>
          </group>
        </group>
        <group name="Transform803" position={[0.1287, 26.2124, 0.1536]} scale={0.1319}>
          <group name="Shape802">
            <group name="vox802">
              <mesh name="vox802_1" geometry={nodes.vox802_1.geometry} material={materials['Material.180']} />
              <mesh name="vox802_2" geometry={nodes.vox802_2.geometry} material={nodes.vox802_2.material} />
              <mesh name="vox802_3" geometry={nodes.vox802_3.geometry} material={nodes.vox802_3.material} />
              <mesh name="vox802_4" geometry={nodes.vox802_4.geometry} material={nodes.vox802_4.material} />
              <mesh name="vox802_5" geometry={nodes.vox802_5.geometry} material={nodes.vox802_5.material} />
            </group>
          </group>
        </group>
        <group name="Transform804" position={[5.0093, 14.7364, 18.0932]} scale={0.1319}>
          <group name="Shape803">
            <group name="vox803">
              <mesh name="vox803_1" geometry={nodes.vox803_1.geometry} material={nodes.vox803_1.material} />
              <mesh name="vox803_2" geometry={nodes.vox803_2.geometry} material={nodes.vox803_2.material} />
              <mesh name="vox803_3" geometry={nodes.vox803_3.geometry} material={nodes.vox803_3.material} />
              <mesh name="vox803_4" geometry={nodes.vox803_4.geometry} material={nodes.vox803_4.material} />
              <mesh name="vox803_5" geometry={nodes.vox803_5.geometry} material={nodes.vox803_5.material} />
              <mesh name="vox803_6" geometry={nodes.vox803_6.geometry} material={nodes.vox803_6.material} />
              <mesh name="vox803_7" geometry={nodes.vox803_7.geometry} material={nodes.vox803_7.material} />
              <mesh name="vox803_8" geometry={nodes.vox803_8.geometry} material={nodes.vox803_8.material} />
              <mesh name="vox803_9" geometry={nodes.vox803_9.geometry} material={nodes.vox803_9.material} />
              <mesh name="vox803_10" geometry={nodes.vox803_10.geometry} material={nodes.vox803_10.material} />
              <mesh name="vox803_11" geometry={nodes.vox803_11.geometry} material={nodes.vox803_11.material} />
              <mesh name="vox803_12" geometry={nodes.vox803_12.geometry} material={nodes.vox803_12.material} />
              <mesh name="vox803_13" geometry={nodes.vox803_13.geometry} material={nodes.vox803_13.material} />
              <mesh name="vox803_14" geometry={nodes.vox803_14.geometry} material={nodes.vox803_14.material} />
              <mesh name="vox803_15" geometry={nodes.vox803_15.geometry} material={nodes.vox803_15.material} />
              <mesh name="vox803_16" geometry={nodes.vox803_16.geometry} material={nodes.vox803_16.material} />
              <mesh name="vox803_17" geometry={nodes.vox803_17.geometry} material={nodes.vox803_17.material} />
              <mesh name="vox803_18" geometry={nodes.vox803_18.geometry} material={nodes.vox803_18.material} />
              <mesh name="vox803_19" geometry={nodes.vox803_19.geometry} material={nodes.vox803_19.material} />
              <mesh name="vox803_20" geometry={nodes.vox803_20.geometry} material={nodes.vox803_20.material} />
            </group>
          </group>
        </group>
        {/*<mesh*/}
        {/*  name="templeCollider"*/}
        {/*  geometry={nodes.templeCollider.geometry}*/}
        {/*  material={nodes.templeCollider.material}*/}
        {/*  position={[9.2409, 0.7881, 28.1735]}*/}
        {/*  rotation={[-1.5703, -0.0057, -1.5708]}*/}
        {/*  scale={[2.2784, 5.7516, 0.0053]}*/}
        {/*/>*/}
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
