/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_5: THREE.Mesh
    mesh_6: THREE.Mesh
    mesh_7: THREE.Mesh
    mesh_8: THREE.Mesh
    mesh_9: THREE.Mesh
    mesh_10: THREE.Mesh
    mesh_11: THREE.Mesh
    mesh_12: THREE.Mesh
    mesh_13: THREE.Mesh
    mesh_14: THREE.Mesh
    mesh_15: THREE.Mesh
    mesh_16: THREE.Mesh
    mesh_17: THREE.Mesh
    mesh_18: THREE.Mesh
    mesh_19: THREE.Mesh
    mesh_20: THREE.Mesh
    mesh_21: THREE.Mesh
    mesh_22: THREE.Mesh
    mesh_23: THREE.Mesh
    mesh_24: THREE.Mesh
    mesh_25: THREE.Mesh
    mesh_26: THREE.Mesh
    mesh_27: THREE.Mesh
    mesh_28: THREE.Mesh
    mesh_29: THREE.Mesh
    mesh_30: THREE.Mesh
    mesh_31: THREE.Mesh
    mesh_32: THREE.Mesh
  }
  materials: {
    ['Material.1']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/cribs-1647412478/cribs.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="cribgltf">
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group>
              <mesh
                name="mesh_0"
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                position={[0, -32, 0]}
              />
              <mesh
                name="mesh_1"
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                position={[16, -32, 0]}
              />
              <mesh
                name="mesh_2"
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
                position={[-32, -16, 0]}
              />
              <mesh
                name="mesh_3"
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                position={[-16, -16, 0]}
              />
              <mesh
                name="mesh_4"
                geometry={nodes.mesh_4.geometry}
                material={nodes.mesh_4.material}
                position={[0, -16, 0]}
              />
              <mesh
                name="mesh_5"
                geometry={nodes.mesh_5.geometry}
                material={nodes.mesh_5.material}
                position={[16, -16, 0]}
              />
              <mesh
                name="mesh_6"
                geometry={nodes.mesh_6.geometry}
                material={nodes.mesh_6.material}
                position={[-32, 0, 0]}
              />
              <mesh
                name="mesh_7"
                geometry={nodes.mesh_7.geometry}
                material={nodes.mesh_7.material}
                position={[-16, 0, 0]}
              />
              <mesh name="mesh_8" geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
              <mesh
                name="mesh_9"
                geometry={nodes.mesh_9.geometry}
                material={nodes.mesh_9.material}
                position={[-32, 16, 0]}
              />
              <mesh
                name="mesh_10"
                geometry={nodes.mesh_10.geometry}
                material={nodes.mesh_10.material}
                position={[-16, 16, 0]}
              />
              <mesh
                name="mesh_11"
                geometry={nodes.mesh_11.geometry}
                material={nodes.mesh_11.material}
                position={[0, 16, 0]}
              />
              <mesh
                name="mesh_12"
                geometry={nodes.mesh_12.geometry}
                material={nodes.mesh_12.material}
                position={[0, -32, 16]}
              />
              <mesh
                name="mesh_13"
                geometry={nodes.mesh_13.geometry}
                material={nodes.mesh_13.material}
                position={[-32, -16, 16]}
              />
              <mesh
                name="mesh_14"
                geometry={nodes.mesh_14.geometry}
                material={nodes.mesh_14.material}
                position={[-16, -16, 16]}
              />
              <mesh
                name="mesh_15"
                geometry={nodes.mesh_15.geometry}
                material={nodes.mesh_15.material}
                position={[0, -16, 16]}
              />
              <mesh
                name="mesh_16"
                geometry={nodes.mesh_16.geometry}
                material={nodes.mesh_16.material}
                position={[16, -16, 16]}
              />
              <mesh
                name="mesh_17"
                geometry={nodes.mesh_17.geometry}
                material={nodes.mesh_17.material}
                position={[-32, 0, 16]}
              />
              <mesh
                name="mesh_18"
                geometry={nodes.mesh_18.geometry}
                material={nodes.mesh_18.material}
                position={[-16, 0, 16]}
              />
              <mesh
                name="mesh_19"
                geometry={nodes.mesh_19.geometry}
                material={nodes.mesh_19.material}
                position={[0, 0, 16]}
              />
              <mesh
                name="mesh_20"
                geometry={nodes.mesh_20.geometry}
                material={nodes.mesh_20.material}
                position={[-32, 16, 16]}
              />
              <mesh
                name="mesh_21"
                geometry={nodes.mesh_21.geometry}
                material={nodes.mesh_21.material}
                position={[-16, 16, 16]}
              />
              <mesh
                name="mesh_22"
                geometry={nodes.mesh_22.geometry}
                material={nodes.mesh_22.material}
                position={[0, 16, 16]}
              />
              <mesh
                name="mesh_23"
                geometry={nodes.mesh_23.geometry}
                material={nodes.mesh_23.material}
                position={[0, -32, 32]}
              />
              <mesh
                name="mesh_24"
                geometry={nodes.mesh_24.geometry}
                material={nodes.mesh_24.material}
                position={[-16, -16, 32]}
              />
              <mesh
                name="mesh_25"
                geometry={nodes.mesh_25.geometry}
                material={nodes.mesh_25.material}
                position={[0, -16, 32]}
              />
              <mesh
                name="mesh_26"
                geometry={nodes.mesh_26.geometry}
                material={nodes.mesh_26.material}
                position={[16, -16, 32]}
              />
              <mesh
                name="mesh_27"
                geometry={nodes.mesh_27.geometry}
                material={nodes.mesh_27.material}
                position={[-32, 0, 32]}
              />
              <mesh
                name="mesh_28"
                geometry={nodes.mesh_28.geometry}
                material={nodes.mesh_28.material}
                position={[-16, 0, 32]}
              />
              <mesh
                name="mesh_29"
                geometry={nodes.mesh_29.geometry}
                material={nodes.mesh_29.material}
                position={[0, 0, 32]}
              />
              <mesh
                name="mesh_30"
                geometry={nodes.mesh_30.geometry}
                material={nodes.mesh_30.material}
                position={[-32, 16, 32]}
              />
              <mesh
                name="mesh_31"
                geometry={nodes.mesh_31.geometry}
                material={nodes.mesh_31.material}
                position={[-16, 16, 32]}
              />
              <mesh
                name="mesh_32"
                geometry={nodes.mesh_32.geometry}
                material={nodes.mesh_32.material}
                position={[0, 16, 32]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
