/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import {useLimiter, useTrimeshCollision} from "spacesvr";
import {BufferGeometry} from "three";
import {useFrame} from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ['new_space_zay-5']: THREE.Mesh
    ['new_space_zay-6']: THREE.Mesh
    ['new_space_zay-7']: THREE.Mesh
    cube2: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_1']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_2']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_3']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_4']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_5']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_6']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_7']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_8']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_9']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_10']: THREE.Mesh
    ['new_space_zay-6001']: THREE.Mesh
    ['new_space_zay-6002']: THREE.Mesh
    ['new_space_zay-6003']: THREE.Mesh
    ['new_space_zay-50-Air_Vent_1002']: THREE.Mesh
    cube3: THREE.Mesh
    cube4: THREE.Mesh
    cube5: THREE.Mesh
    cube6: THREE.Mesh
    cube1: THREE.Mesh
    cube7: THREE.Mesh
    ['new_space_zay-6004']: THREE.Mesh
    ['new_space_zay-6005']: THREE.Mesh
    ['new_space_zay-6006']: THREE.Mesh
    ['new_space_zay-6007']: THREE.Mesh
    ['new_space_zay-6008']: THREE.Mesh
    ['new_space_zay-1']: THREE.Mesh
    ['new_space_zay-26-Ground_3001']: THREE.Mesh
    ['new_space_zay-1002']: THREE.Mesh
    ['new_space_zay-1003']: THREE.Mesh
    Collider: THREE.Mesh
  }
  materials: {
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.085']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshStandardMaterial
    ['Material.117']: THREE.MeshStandardMaterial
    ['Material.119']: THREE.MeshStandardMaterial
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.081']: THREE.MeshStandardMaterial
    ['Material.082']: THREE.MeshStandardMaterial
    ['Material.083']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.092']: THREE.MeshStandardMaterial
    ['Material.093']: THREE.MeshStandardMaterial
    ['Material.094']: THREE.MeshStandardMaterial
    ['Material.095']: THREE.MeshStandardMaterial
    ['Material.103']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.116']: THREE.MeshStandardMaterial
    ['Material.118']: THREE.MeshStandardMaterial
    ['Material.120']: THREE.MeshStandardMaterial
    ['Material.122']: THREE.MeshStandardMaterial
    ['Material.124']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/station-1648250133/station.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult
  const group = useRef<THREE.Group>(),
    cube1 = useRef<THREE.Mesh>(),
    cube2 = useRef<THREE.Mesh>(),
    cube3 = useRef<THREE.Mesh>(),
    cube4 = useRef<THREE.Mesh>(),
    cube5 = useRef<THREE.Mesh>(),
    cube6 = useRef<THREE.Mesh>(),
    cube7 = useRef<THREE.Mesh>();

  const limiter = useLimiter(30);
  useFrame(({ clock }, delta) => {
    if (!limiter.isReady(clock)
      || !cube1.current
      || !cube2.current
      || !cube3.current
      || !cube4.current
      || !cube5.current
      || !cube6.current
      || !cube7.current
    ) return;
    cube1.current.rotation.x += delta/5;
    cube2.current.rotation.x -= delta/5;
    cube3.current.rotation.x += delta/5;
    cube4.current.rotation.x += delta/5;
    cube5.current.rotation.x -= delta/5;
    cube6.current.rotation.x -= delta/5;
    cube7.current.rotation.x += delta/5;
  })

  useTrimeshCollision((nodes["Collider"].geometry as BufferGeometry)
    .clone()
    .scale(39.137, 0.3651, 56.7515)
    .translate(4.0458, 0.2531, -33.008)
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="new_space_zay-5"
          geometry={nodes['new_space_zay-5'].geometry}
          material={materials['Material.044']}
          position={[18.8011, -13.6884, -53.9982]}
        />
        <mesh
          name="new_space_zay-6"
          geometry={nodes['new_space_zay-6'].geometry}
          material={materials['Material.042']}
          position={[18.8011, -13.6884, -53.9982]}
        />
        <mesh
          name="new_space_zay-7"
          geometry={nodes['new_space_zay-7'].geometry}
          material={materials['Material.043']}
          position={[18.8011, -13.6884, -53.9982]}
        />
        <mesh
          ref={cube2}
          name="cube2"
          geometry={nodes.cube2.geometry}
          material={materials['Material.052']}
          position={[-13.8797, 5.6256, -61.3965]}
          rotation={[0.3668, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <group name="lights" position={[-0.9446, 2.8738, -14.2171]} rotation={[0, 1.5649, 0]}>
          <mesh
            name="new_space_zay-45-Streetlamp_2003"
            geometry={nodes['new_space_zay-45-Streetlamp_2003'].geometry}
            material={materials['Material.055']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_1"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_1'].geometry}
            material={materials['Material.054']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_2"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_2'].geometry}
            material={materials['Material.056']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_3"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_3'].geometry}
            material={materials['Material.084']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_4"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_4'].geometry}
            material={materials['Material.085']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_5"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_5'].geometry}
            material={materials['Material.086']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_6"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_6'].geometry}
            material={materials['Material.117']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_7"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_7'].geometry}
            material={materials['Material.119']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_8"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_8'].geometry}
            material={materials['Material.121']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_9"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_9'].geometry}
            material={materials['Material.129']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_10"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_10'].geometry}
            material={materials['Material.130']}
          />
        </group>
        <mesh
          name="new_space_zay-6001"
          geometry={nodes['new_space_zay-6001'].geometry}
          material={materials['Material.081']}
          position={[-0.1154, -3.3549, -14.158]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6002"
          geometry={nodes['new_space_zay-6002'].geometry}
          material={materials['Material.082']}
          position={[-0.1154, -3.3549, -6.3333]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6003"
          geometry={nodes['new_space_zay-6003'].geometry}
          material={materials['Material.083']}
          position={[-0.1154, -3.3549, -22.6274]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-50-Air_Vent_1002"
          geometry={nodes['new_space_zay-50-Air_Vent_1002'].geometry}
          material={materials['Material.088']}
          position={[-5.9772, -2.4217, -30.111]}
          rotation={[3.1371, 1.5685, 0]}
        />
        <mesh
          ref={cube3}
          name="cube3"
          geometry={nodes.cube3.geometry}
          material={materials['Material.092']}
          position={[-4.0477, 5.6256, -61.3965]}
          rotation={[2.7549, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube4}
          name="cube4"
          geometry={nodes.cube4.geometry}
          material={materials['Material.093']}
          position={[5.1795, 5.6256, -61.3965]}
          rotation={[-1.5124, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube5}
          name="cube5"
          geometry={nodes.cube5.geometry}
          material={materials['Material.094']}
          position={[15.0483, 5.6256, -61.3965]}
          rotation={[2.1659, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube6}
          name="cube6"
          geometry={nodes.cube6.geometry}
          material={materials['Material.095']}
          position={[25.0214, 5.6256, -61.3965]}
          rotation={[-0.3494, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube1}
          name="cube1"
          geometry={nodes.cube1.geometry}
          material={materials['Material.103']}
          position={[-25.5272, 5.6256, -61.3865]}
          rotation={[-2.4962, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube7}
          name="cube7"
          geometry={nodes.cube7.geometry}
          material={materials['Material.104']}
          position={[35.4726, 5.6256, -61.3965]}
          rotation={[2.5559, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          name="new_space_zay-6004"
          geometry={nodes['new_space_zay-6004'].geometry}
          material={materials['Material.116']}
          position={[9.7772, -3.3549, -37.1926]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6005"
          geometry={nodes['new_space_zay-6005'].geometry}
          material={materials['Material.118']}
          position={[9.7772, -3.3549, -55.0624]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6006"
          geometry={nodes['new_space_zay-6006'].geometry}
          material={materials['Material.120']}
          position={[9.984, -3.3549, -46.4067]}
          rotation={[0, 1.5679, 0]}
        />
        <mesh
          name="new_space_zay-6007"
          geometry={nodes['new_space_zay-6007'].geometry}
          material={materials['Material.122']}
          position={[20.0638, -3.3549, -61.3563]}
          rotation={[0, -0.0002, 0]}
        />
        <mesh
          name="new_space_zay-6008"
          geometry={nodes['new_space_zay-6008'].geometry}
          material={materials['Material.124']}
          position={[0.7146, -3.3549, -61.3563]}
          rotation={[0, -0.0002, 0]}
        />
        <mesh
          name="new_space_zay-1"
          geometry={nodes['new_space_zay-1'].geometry}
          material={materials['Material.131']}
          position={[3.5171, 0.3079, -31.3205]}
        />
        <mesh
          name="new_space_zay-26-Ground_3001"
          geometry={nodes['new_space_zay-26-Ground_3001'].geometry}
          material={materials['Material.001']}
          position={[-0.0105, 0.0486, 0]}
        />
        <mesh
          name="new_space_zay-1002"
          geometry={nodes['new_space_zay-1002'].geometry}
          material={materials['Material.046']}
          position={[0.005, 0.2324, -9.6525]}
        />
        <mesh
          name="new_space_zay-1003"
          geometry={nodes['new_space_zay-1003'].geometry}
          material={materials['Material.047']}
          position={[0.005, 0.2324, -19.5447]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
