/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useMemo, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import {useLimiter, useTrimeshCollision} from "spacesvr";
import {useFrame} from "@react-three/fiber";
import {BufferGeometry} from "three";
import {useWorld} from "../components/WorldState";

type GLTFResult = GLTF & {
  nodes: {
    ['new_space_zay-6001']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_1']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_2']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_3']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_4']: THREE.Mesh
    ['new_space_zay-50-Air_Vent_1002']: THREE.Mesh
    ['new_space_zay-1']: THREE.Mesh
    Collider: THREE.Mesh
    cube1: THREE.Mesh
    cube1light: THREE.Mesh
    cube2: THREE.Mesh
    cube2light: THREE.Mesh
    cube3: THREE.Mesh
    cube3light: THREE.Mesh
    cube4: THREE.Mesh
    cube4light: THREE.Mesh
    cube5: THREE.Mesh
    cube5light: THREE.Mesh
    cube6: THREE.Mesh
    cube6light: THREE.Mesh
    cube7: THREE.Mesh
    cube7light: THREE.Mesh
    ['new_space_zay-6010']: THREE.Mesh
    ['new_space_zay-6011']: THREE.Mesh
    ['new_space_zay-6014']: THREE.Mesh
    ['new_space_zay-6015']: THREE.Mesh
    ['new_space_zay-6003']: THREE.Mesh
    ['new_space_zay-6005']: THREE.Mesh
    ['new_space_zay-6006']: THREE.Mesh
    ['new_space_zay-6018']: THREE.Mesh
    ['new_space_zay-6019']: THREE.Mesh
    ['new_space_zay-6022']: THREE.Mesh
    ['new_space_zay-6002']: THREE.Mesh
  }
  materials: {
    ['Material.075']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    ['Material.076']: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.087']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/station-1648346789/station.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {

  const { bloomObjects, setBloomObjects } = useWorld();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult
  const group = useRef<THREE.Group>(),
    cube1 = useRef<THREE.Mesh>(),
    cube2 = useRef<THREE.Mesh>(),
    cube3 = useRef<THREE.Mesh>(),
    cube4 = useRef<THREE.Mesh>(),
    cube5 = useRef<THREE.Mesh>(),
    cube6 = useRef<THREE.Mesh>(),
    cube7 = useRef<THREE.Mesh>(),
    lightMesh1 = useRef<THREE.Mesh>(),
    lightMesh2 = useRef<THREE.Mesh>(),
    lightMesh3 = useRef<THREE.Mesh>(),
    lightMesh4 = useRef<THREE.Mesh>(),
    lightMesh5 = useRef<THREE.Mesh>(),
    lightMesh6 = useRef<THREE.Mesh>(),
    lightMesh7 = useRef<THREE.Mesh>();

  useMemo(() => {
    setBloomObjects([...bloomObjects, lightMesh1, lightMesh2, lightMesh3, lightMesh4, lightMesh5, lightMesh6, lightMesh7])
  }, [lightMesh1, lightMesh2, lightMesh3, lightMesh4, lightMesh5, lightMesh6, lightMesh7])

  const limiter = useLimiter(30);
  useFrame(({ clock }, delta) => {
    if (!limiter.isReady(clock)
      || !cube1.current
      || !cube2.current
      || !cube3.current
      || !cube4.current
      || !cube5.current
      || !cube6.current
      || !cube7.current
      || !lightMesh1.current
      || !lightMesh2.current
      || !lightMesh3.current
      || !lightMesh4.current
      || !lightMesh5.current
      || !lightMesh6.current
      || !lightMesh7.current
    ) return;
    cube1.current.rotation.x += delta/5;
    cube2.current.rotation.x -= delta/5;
    cube3.current.rotation.x += delta/5;
    cube4.current.rotation.x += delta/5;
    cube5.current.rotation.x -= delta/5;
    cube6.current.rotation.x -= delta/5;
    cube7.current.rotation.x += delta/5;
    lightMesh1.current.rotation.x = cube1.current.rotation.x;
    lightMesh2.current.rotation.x = cube2.current.rotation.x;
    lightMesh3.current.rotation.x = cube3.current.rotation.x;
    lightMesh4.current.rotation.x = cube4.current.rotation.x;
    lightMesh5.current.rotation.x = cube5.current.rotation.x;
    lightMesh6.current.rotation.x = cube6.current.rotation.x;
    lightMesh7.current.rotation.x = cube7.current.rotation.x;
  })

  // useTrimeshCollision((nodes["Collider"].geometry as BufferGeometry)
  //   .clone()
  //   .scale(39.137, 0.3651, 56.7515)
  //   .translate(4.0458, 0.2531, -33.008)
  // )

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="new_space_zay-6001"
          geometry={nodes['new_space_zay-6001'].geometry}
          material={nodes['new_space_zay-6001'].material}
          position={[-0.055, -3.3299, -14.3641]}
          rotation={[0, -1.5701, 0]}
        />
        <group name="lights" position={[-0.9446, 2.8784, -14.2171]} rotation={[0, 1.5649, 0]}>
          <mesh
            name="new_space_zay-45-Streetlamp_2003"
            geometry={nodes['new_space_zay-45-Streetlamp_2003'].geometry}
            material={materials['Material.055']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_1"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_1'].geometry}
            material={materials['Material.084']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_2"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_2'].geometry}
            material={materials['Material.121']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_3"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_3'].geometry}
            material={materials['Material.129']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_4"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_4'].geometry}
            material={materials['Material.130']}
          />
        </group>
        <mesh
          name="new_space_zay-50-Air_Vent_1002"
          geometry={nodes['new_space_zay-50-Air_Vent_1002'].geometry}
          material={materials['Material.088']}
          position={[-5.9772, -2.4217, -30.111]}
          rotation={[3.1371, 1.5685, 0]}
        />
        <mesh
          name="new_space_zay-1"
          geometry={nodes['new_space_zay-1'].geometry}
          material={materials['Material.131']}
          position={[3.5171, 0.3079, -31.3205]}
        />
        <group>
          <mesh
            ref={cube1}
            name="cube1"
            geometry={nodes.cube1.geometry}
            material={nodes.cube1.material}
            position={[-24.797, 5.6256, -61.4191]}
            rotation={[-2.4313, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh1}
            name="cube1light"
            geometry={nodes.cube1light.geometry}
            material={nodes.cube1light.material}
            position={[-24.797, 5.6256, -61.4191]}
            rotation={[-2.4313, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <group>
          <mesh
            ref={cube2}
            name="cube2"
            geometry={nodes.cube2.geometry}
            material={nodes.cube2.material}
            position={[-14.7537, 5.6256, -61.4191]}
            rotation={[0.0697, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh2}
            name="cube2light"
            geometry={nodes.cube2light.geometry}
            material={nodes.cube2light.material}
            position={[-14.7537, 5.6256, -61.4191]}
            rotation={[0.0697, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <group>
          <mesh
            ref={cube3}
            name="cube3"
            geometry={nodes.cube3.geometry}
            material={nodes.cube3.material}
            position={[-4.6635, 5.6256, -61.4191]}
            rotation={[2.7674, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh3}
            name="cube3light"
            geometry={nodes.cube3light.geometry}
            material={nodes.cube3light.material}
            position={[-4.6635, 5.6256, -61.4191]}
            rotation={[2.7674, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <group>
          <mesh
            ref={cube4}
            name="cube4"
            geometry={nodes.cube4.geometry}
            material={nodes.cube4.material}
            position={[5.3608, 5.6256, -61.4191]}
            rotation={[-1.3832, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh4}
            name="cube4light"
            geometry={nodes.cube4light.geometry}
            material={nodes.cube4light.material}
            position={[5.3608, 5.6256, -61.4191]}
            rotation={[-1.3832, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <group>
          <mesh
            ref={cube5}
            name="cube5"
            geometry={nodes.cube5.geometry}
            material={nodes.cube5.material}
            position={[15.3836, 5.6256, -61.4191]}
            rotation={[2.1326, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh5}
            name="cube5light"
            geometry={nodes.cube5light.geometry}
            material={nodes.cube5light.material}
            position={[15.3836, 5.6256, -61.4191]}
            rotation={[2.1326, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <group>
          <mesh
            ref={cube6}
            name="cube6"
            geometry={nodes.cube6.geometry}
            material={nodes.cube6.material}
            position={[25.4678, 5.6256, -61.4191]}
            rotation={[-0.4182, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh6}
            name="cube6light"
            geometry={nodes.cube6light.geometry}
            material={nodes.cube6light.material}
            position={[25.4678, 5.6256, -61.4191]}
            rotation={[-0.4182, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <group>
          <mesh
            ref={cube7}
            name="cube7"
            geometry={nodes.cube7.geometry}
            material={nodes.cube7.material}
            position={[35.4726, 5.6256, -61.4191]}
            rotation={[2.5559, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
          <mesh
            ref={lightMesh7}
            name="cube7light"
            geometry={nodes.cube7light.geometry}
            material={nodes.cube7light.material}
            position={[35.4726, 5.6256, -61.4191]}
            rotation={[2.5559, 0, 0]}
            scale={[2.0911, 3.0443, 3.008]}
          />
        </group>
        <mesh
          name="new_space_zay-6010"
          geometry={nodes['new_space_zay-6010'].geometry}
          material={materials['Material.061']}
          position={[12.9675, -3.3299, -29.9691]}
        />
        <mesh
          name="new_space_zay-6011"
          geometry={nodes['new_space_zay-6011'].geometry}
          material={materials['Material.072']}
          position={[5.4579, -3.3299, -30.0206]}
        />
        <mesh
          name="new_space_zay-6014"
          geometry={nodes['new_space_zay-6014'].geometry}
          material={materials['Material.073']}
          position={[-2.1313, -3.3299, -29.9286]}
        />
        <mesh
          name="new_space_zay-6015"
          geometry={nodes['new_space_zay-6015'].geometry}
          material={materials['Material.074']}
          position={[-0.0593, -3.3299, -22.4768]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6003"
          geometry={nodes['new_space_zay-6003'].geometry}
          material={materials['Material.076']}
          position={[-0.0593, -3.3299, -6.6022]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6005"
          geometry={nodes['new_space_zay-6005'].geometry}
          material={materials['Material.077']}
          position={[9.8094, -3.3299, -37.6488]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6006"
          geometry={nodes['new_space_zay-6006'].geometry}
          material={materials['Material.078']}
          position={[9.7689, -3.3299, -46.1483]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6018"
          geometry={nodes['new_space_zay-6018'].geometry}
          material={materials['Material.079']}
          position={[9.7689, -3.3299, -55.5346]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6019"
          geometry={nodes['new_space_zay-6019'].geometry}
          material={materials['Material.080']}
          position={[20.1773, -3.3299, -61.4222]}
        />
        <mesh
          name="new_space_zay-6022"
          geometry={nodes['new_space_zay-6022'].geometry}
          material={materials['Material.087']}
          position={[0.4637, -3.3299, -61.4222]}
        />
        <mesh
          name="new_space_zay-6002"
          geometry={nodes['new_space_zay-6002'].geometry}
          material={nodes['new_space_zay-6002'].material}
          position={[-0.0593, -3.3299, -14.3641]}
          rotation={[0, -1.5701, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
