/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import {useFrame} from "@react-three/fiber";
import {useLimiter, useTrimeshCollision} from "spacesvr";
import {BufferGeometry} from "three";

type GLTFResult = GLTF & {
  nodes: {
    ['new_space_zay-5']: THREE.Mesh
    ['new_space_zay-6']: THREE.Mesh
    ['new_space_zay-7']: THREE.Mesh
    cube2: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_1']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_2']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_3']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_4']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_5']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_6']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_7']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_8']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_9']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_10']: THREE.Mesh
    ['new_space_zay-6001']: THREE.Mesh
    ['new_space_zay-6002']: THREE.Mesh
    ['new_space_zay-6003']: THREE.Mesh
    ['new_space_zay-50-Air_Vent_1002']: THREE.Mesh
    cube3: THREE.Mesh
    cube4: THREE.Mesh
    cube5: THREE.Mesh
    cube6: THREE.Mesh
    cube1: THREE.Mesh
    cube7: THREE.Mesh
    ['new_space_zay-1007']: THREE.Mesh
    ['new_space_zay-1007_1']: THREE.Mesh
    ['new_space_zay-1007_2']: THREE.Mesh
    ['new_space_zay-1007_3']: THREE.Mesh
    ['new_space_zay-1007_4']: THREE.Mesh
    ['new_space_zay-1007_5']: THREE.Mesh
    ['new_space_zay-1007_6']: THREE.Mesh
    ['new_space_zay-1007_7']: THREE.Mesh
    ['new_space_zay-1007_8']: THREE.Mesh
    ['new_space_zay-1007_9']: THREE.Mesh
    ['new_space_zay-1007_10']: THREE.Mesh
    ['new_space_zay-1007_11']: THREE.Mesh
    ['new_space_zay-1007_12']: THREE.Mesh
    ['new_space_zay-1007_13']: THREE.Mesh
    ['new_space_zay-1007_14']: THREE.Mesh
    ['new_space_zay-1007_15']: THREE.Mesh
    ['new_space_zay-1007_16']: THREE.Mesh
    ['new_space_zay-1007_17']: THREE.Mesh
    ['new_space_zay-1007_18']: THREE.Mesh
    ['new_space_zay-1007_19']: THREE.Mesh
    ['new_space_zay-1007_20']: THREE.Mesh
    ['new_space_zay-1007_21']: THREE.Mesh
    ['new_space_zay-1007_22']: THREE.Mesh
    ['new_space_zay-1007_23']: THREE.Mesh
    ['new_space_zay-1007_24']: THREE.Mesh
    ['new_space_zay-1007_25']: THREE.Mesh
    ['new_space_zay-1007_26']: THREE.Mesh
    ['new_space_zay-1007_27']: THREE.Mesh
    ['new_space_zay-1007_28']: THREE.Mesh
    ['new_space_zay-1007_29']: THREE.Mesh
    ['new_space_zay-1007_30']: THREE.Mesh
    ['new_space_zay-1007_31']: THREE.Mesh
    ['new_space_zay-1007_32']: THREE.Mesh
    ['new_space_zay-1007_33']: THREE.Mesh
    ['new_space_zay-1007_34']: THREE.Mesh
    ['new_space_zay-1007_35']: THREE.Mesh
    ['new_space_zay-1007_36']: THREE.Mesh
    ['new_space_zay-1007_37']: THREE.Mesh
    ['new_space_zay-1007_38']: THREE.Mesh
    ['new_space_zay-1007_39']: THREE.Mesh
    ['new_space_zay-1007_40']: THREE.Mesh
    ['new_space_zay-1007_41']: THREE.Mesh
    ['new_space_zay-1007_42']: THREE.Mesh
    ['new_space_zay-1007_43']: THREE.Mesh
    ['new_space_zay-1007_44']: THREE.Mesh
    ['new_space_zay-1007_45']: THREE.Mesh
    ['new_space_zay-1007_46']: THREE.Mesh
    ['new_space_zay-1007_47']: THREE.Mesh
    ['new_space_zay-1007_48']: THREE.Mesh
    ['new_space_zay-6004']: THREE.Mesh
    ['new_space_zay-6005']: THREE.Mesh
    ['new_space_zay-6006']: THREE.Mesh
    ['new_space_zay-6007']: THREE.Mesh
    ['new_space_zay-6008']: THREE.Mesh
  }
  materials: {
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.085']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshStandardMaterial
    ['Material.117']: THREE.MeshStandardMaterial
    ['Material.119']: THREE.MeshStandardMaterial
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.081']: THREE.MeshStandardMaterial
    ['Material.082']: THREE.MeshStandardMaterial
    ['Material.083']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.092']: THREE.MeshStandardMaterial
    ['Material.093']: THREE.MeshStandardMaterial
    ['Material.094']: THREE.MeshStandardMaterial
    ['Material.095']: THREE.MeshStandardMaterial
    ['Material.103']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.105']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.087']: THREE.MeshStandardMaterial
    ['Material.089']: THREE.MeshStandardMaterial
    ['Material.090']: THREE.MeshStandardMaterial
    ['Material.096']: THREE.MeshStandardMaterial
    ['Material.098']: THREE.MeshStandardMaterial
    ['Material.099']: THREE.MeshStandardMaterial
    ['Material.100']: THREE.MeshStandardMaterial
    ['Material.101']: THREE.MeshStandardMaterial
    ['Material.102']: THREE.MeshStandardMaterial
    ['Material.125']: THREE.MeshStandardMaterial
    ['Material.126']: THREE.MeshStandardMaterial
    ['Material.127']: THREE.MeshStandardMaterial
    ['Material.128']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['Material.064']: THREE.MeshStandardMaterial
    ['Material.065']: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.067']: THREE.MeshStandardMaterial
    ['Material.068']: THREE.MeshStandardMaterial
    ['Material.069']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    ['Material.075']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.076']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.106']: THREE.MeshStandardMaterial
    ['Material.107']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
    ['Material.109']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.111']: THREE.MeshStandardMaterial
    ['Material.112']: THREE.MeshStandardMaterial
    ['Material.113']: THREE.MeshStandardMaterial
    ['Material.114']: THREE.MeshStandardMaterial
    ['Material.115']: THREE.MeshStandardMaterial
    ['Material.116']: THREE.MeshStandardMaterial
    ['Material.118']: THREE.MeshStandardMaterial
    ['Material.120']: THREE.MeshStandardMaterial
    ['Material.122']: THREE.MeshStandardMaterial
    ['Material.124']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/station-1648005330/station.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {

  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult
  const group = useRef<THREE.Group>(),
    cube1 = useRef<THREE.Mesh>(),
    cube2 = useRef<THREE.Mesh>(),
    cube3 = useRef<THREE.Mesh>(),
    cube4 = useRef<THREE.Mesh>(),
    cube5 = useRef<THREE.Mesh>(),
    cube6 = useRef<THREE.Mesh>(),
    cube7 = useRef<THREE.Mesh>();

  const limiter = useLimiter(30);
  useFrame(({ clock }) => {
    if (!limiter.isReady(clock)
      || !cube1.current
      || !cube2.current
      || !cube3.current
      || !cube4.current
      || !cube5.current
      || !cube6.current
      || !cube7.current
    ) return;
    cube1.current.rotation.x = clock.getElapsedTime()/5
    cube2.current.rotation.x = (clock.getElapsedTime()+1)/5
    cube3.current.rotation.x = (clock.getElapsedTime()+2)/5
    cube4.current.rotation.x = (clock.getElapsedTime()+3)/5
    cube5.current.rotation.x = (clock.getElapsedTime()+4)/5
    cube6.current.rotation.x = (clock.getElapsedTime()+5)/5
    cube7.current.rotation.x = (clock.getElapsedTime()+6)/5
  })

  useTrimeshCollision((nodes[`new_space_zay-1007`].geometry as BufferGeometry)
    .clone()
    .rotateY(-1.5705)
    .translate(19.9862, 0.2206-1, -61.4787)
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="new_space_zay-5"
          geometry={nodes['new_space_zay-5'].geometry}
          material={materials['Material.044']}
          position={[18.8011, -13.6884, -53.9982]}
        />
        <mesh
          name="new_space_zay-6"
          geometry={nodes['new_space_zay-6'].geometry}
          material={materials['Material.042']}
          position={[18.8011, -13.6884, -53.9982]}
        />
        <mesh
          name="new_space_zay-7"
          geometry={nodes['new_space_zay-7'].geometry}
          material={materials['Material.043']}
          position={[18.8011, -13.6884, -53.9982]}
        />
        <mesh
          ref={cube2}
          name="cube2"
          geometry={nodes.cube2.geometry}
          material={materials['Material.052']}
          position={[-13.8797, 5.6256, -61.7549]}
          rotation={[0.3668, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <group name="lights" position={[-0.9446, 2.8738, -14.2171]} rotation={[0, 1.5649, 0]}>
          <mesh
            name="new_space_zay-45-Streetlamp_2003"
            geometry={nodes['new_space_zay-45-Streetlamp_2003'].geometry}
            material={materials['Material.055']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_1"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_1'].geometry}
            material={materials['Material.054']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_2"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_2'].geometry}
            material={materials['Material.056']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_3"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_3'].geometry}
            material={materials['Material.084']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_4"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_4'].geometry}
            material={materials['Material.085']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_5"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_5'].geometry}
            material={materials['Material.086']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_6"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_6'].geometry}
            material={materials['Material.117']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_7"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_7'].geometry}
            material={materials['Material.119']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_8"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_8'].geometry}
            material={materials['Material.121']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_9"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_9'].geometry}
            material={materials['Material.129']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_10"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_10'].geometry}
            material={materials['Material.130']}
          />
        </group>
        <mesh
          name="new_space_zay-6001"
          geometry={nodes['new_space_zay-6001'].geometry}
          material={materials['Material.081']}
          position={[-0.1154, -3.3549, -14.158]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6002"
          geometry={nodes['new_space_zay-6002'].geometry}
          material={materials['Material.082']}
          position={[-0.1154, -3.3549, -6.3333]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6003"
          geometry={nodes['new_space_zay-6003'].geometry}
          material={materials['Material.083']}
          position={[-0.1154, -3.3549, -22.6274]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-50-Air_Vent_1002"
          geometry={nodes['new_space_zay-50-Air_Vent_1002'].geometry}
          material={materials['Material.088']}
          position={[-5.9772, -2.4217, -30.111]}
          rotation={[3.1371, 1.5685, 0]}
        />
        <mesh
          ref={cube3}
          name="cube3"
          geometry={nodes.cube3.geometry}
          material={materials['Material.092']}
          position={[-4.0477, 5.6256, -61.7549]}
          rotation={[2.7549, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube4}
          name="cube4"
          geometry={nodes.cube4.geometry}
          material={materials['Material.093']}
          position={[5.1795, 5.6256, -61.7549]}
          rotation={[-1.5124, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube5}
          name="cube5"
          geometry={nodes.cube5.geometry}
          material={materials['Material.094']}
          position={[15.0483, 5.6256, -61.7549]}
          rotation={[2.1659, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube6}
          name="cube6"
          geometry={nodes.cube6.geometry}
          material={materials['Material.095']}
          position={[25.0214, 5.6256, -61.7549]}
          rotation={[-0.3494, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube1}
          name="cube1"
          geometry={nodes.cube1.geometry}
          material={materials['Material.103']}
          position={[-25.5272, 5.6256, -61.7549]}
          rotation={[-2.4962, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube7}
          name="cube7"
          geometry={nodes.cube7.geometry}
          material={materials['Material.104']}
          position={[35.4726, 5.6256, -61.7549]}
          rotation={[2.5559, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <group name="collisions" position={[19.9862, 0.2206, -61.4787]} rotation={[0, -1.5705, 0]}>
          <mesh
            name="new_space_zay-1007"
            geometry={nodes['new_space_zay-1007'].geometry}
            material={materials['Material.105']}
          />
          <mesh
            name="new_space_zay-1007_1"
            geometry={nodes['new_space_zay-1007_1'].geometry}
            material={materials['Material.046']}
          />
          <mesh
            name="new_space_zay-1007_2"
            geometry={nodes['new_space_zay-1007_2'].geometry}
            material={materials['Material.045']}
          />
          <mesh
            name="new_space_zay-1007_3"
            geometry={nodes['new_space_zay-1007_3'].geometry}
            material={materials['Material.047']}
          />
          <mesh
            name="new_space_zay-1007_4"
            geometry={nodes['new_space_zay-1007_4'].geometry}
            material={materials['Material.048']}
          />
          <mesh
            name="new_space_zay-1007_5"
            geometry={nodes['new_space_zay-1007_5'].geometry}
            material={materials['Material.057']}
          />
          <mesh
            name="new_space_zay-1007_6"
            geometry={nodes['new_space_zay-1007_6'].geometry}
            material={materials['Material.087']}
          />
          <mesh
            name="new_space_zay-1007_7"
            geometry={nodes['new_space_zay-1007_7'].geometry}
            material={materials['Material.089']}
          />
          <mesh
            name="new_space_zay-1007_8"
            geometry={nodes['new_space_zay-1007_8'].geometry}
            material={materials['Material.090']}
          />
          <mesh
            name="new_space_zay-1007_9"
            geometry={nodes['new_space_zay-1007_9'].geometry}
            material={materials['Material.096']}
          />
          <mesh
            name="new_space_zay-1007_10"
            geometry={nodes['new_space_zay-1007_10'].geometry}
            material={materials['Material.098']}
          />
          <mesh
            name="new_space_zay-1007_11"
            geometry={nodes['new_space_zay-1007_11'].geometry}
            material={materials['Material.099']}
          />
          <mesh
            name="new_space_zay-1007_12"
            geometry={nodes['new_space_zay-1007_12'].geometry}
            material={materials['Material.100']}
          />
          <mesh
            name="new_space_zay-1007_13"
            geometry={nodes['new_space_zay-1007_13'].geometry}
            material={materials['Material.101']}
          />
          <mesh
            name="new_space_zay-1007_14"
            geometry={nodes['new_space_zay-1007_14'].geometry}
            material={materials['Material.102']}
          />
          <mesh
            name="new_space_zay-1007_15"
            geometry={nodes['new_space_zay-1007_15'].geometry}
            material={materials['Material.125']}
          />
          <mesh
            name="new_space_zay-1007_16"
            geometry={nodes['new_space_zay-1007_16'].geometry}
            material={materials['Material.126']}
          />
          <mesh
            name="new_space_zay-1007_17"
            geometry={nodes['new_space_zay-1007_17'].geometry}
            material={materials['Material.127']}
          />
          <mesh
            name="new_space_zay-1007_18"
            geometry={nodes['new_space_zay-1007_18'].geometry}
            material={materials['Material.128']}
          />
          <mesh
            name="new_space_zay-1007_19"
            geometry={nodes['new_space_zay-1007_19'].geometry}
            material={materials['Material.062']}
          />
          <mesh
            name="new_space_zay-1007_20"
            geometry={nodes['new_space_zay-1007_20'].geometry}
            material={materials['Material.063']}
          />
          <mesh
            name="new_space_zay-1007_21"
            geometry={nodes['new_space_zay-1007_21'].geometry}
            material={materials['Material.064']}
          />
          <mesh
            name="new_space_zay-1007_22"
            geometry={nodes['new_space_zay-1007_22'].geometry}
            material={materials['Material.065']}
          />
          <mesh
            name="new_space_zay-1007_23"
            geometry={nodes['new_space_zay-1007_23'].geometry}
            material={materials['Material.066']}
          />
          <mesh
            name="new_space_zay-1007_24"
            geometry={nodes['new_space_zay-1007_24'].geometry}
            material={materials['Material.067']}
          />
          <mesh
            name="new_space_zay-1007_25"
            geometry={nodes['new_space_zay-1007_25'].geometry}
            material={materials['Material.068']}
          />
          <mesh
            name="new_space_zay-1007_26"
            geometry={nodes['new_space_zay-1007_26'].geometry}
            material={materials['Material.069']}
          />
          <mesh
            name="new_space_zay-1007_27"
            geometry={nodes['new_space_zay-1007_27'].geometry}
            material={materials['Material.072']}
          />
          <mesh
            name="new_space_zay-1007_28"
            geometry={nodes['new_space_zay-1007_28'].geometry}
            material={materials['Material.073']}
          />
          <mesh
            name="new_space_zay-1007_29"
            geometry={nodes['new_space_zay-1007_29'].geometry}
            material={materials['Material.074']}
          />
          <mesh
            name="new_space_zay-1007_30"
            geometry={nodes['new_space_zay-1007_30'].geometry}
            material={materials['Material.075']}
          />
          <mesh
            name="new_space_zay-1007_31"
            geometry={nodes['new_space_zay-1007_31'].geometry}
            material={materials['Material.080']}
          />
          <mesh
            name="new_space_zay-1007_32"
            geometry={nodes['new_space_zay-1007_32'].geometry}
            material={materials['Material.079']}
          />
          <mesh
            name="new_space_zay-1007_33"
            geometry={nodes['new_space_zay-1007_33'].geometry}
            material={materials['Material.078']}
          />
          <mesh
            name="new_space_zay-1007_34"
            geometry={nodes['new_space_zay-1007_34'].geometry}
            material={materials['Material.077']}
          />
          <mesh
            name="new_space_zay-1007_35"
            geometry={nodes['new_space_zay-1007_35'].geometry}
            material={materials['Material.060']}
          />
          <mesh
            name="new_space_zay-1007_36"
            geometry={nodes['new_space_zay-1007_36'].geometry}
            material={materials['Material.061']}
          />
          <mesh
            name="new_space_zay-1007_37"
            geometry={nodes['new_space_zay-1007_37'].geometry}
            material={materials['Material.076']}
          />
          <mesh
            name="new_space_zay-1007_38"
            geometry={nodes['new_space_zay-1007_38'].geometry}
            material={materials['Material.059']}
          />
          <mesh
            name="new_space_zay-1007_39"
            geometry={nodes['new_space_zay-1007_39'].geometry}
            material={materials['Material.106']}
          />
          <mesh
            name="new_space_zay-1007_40"
            geometry={nodes['new_space_zay-1007_40'].geometry}
            material={materials['Material.107']}
          />
          <mesh
            name="new_space_zay-1007_41"
            geometry={nodes['new_space_zay-1007_41'].geometry}
            material={materials['Material.108']}
          />
          <mesh
            name="new_space_zay-1007_42"
            geometry={nodes['new_space_zay-1007_42'].geometry}
            material={materials['Material.109']}
          />
          <mesh
            name="new_space_zay-1007_43"
            geometry={nodes['new_space_zay-1007_43'].geometry}
            material={materials['Material.110']}
          />
          <mesh
            name="new_space_zay-1007_44"
            geometry={nodes['new_space_zay-1007_44'].geometry}
            material={materials['Material.111']}
          />
          <mesh
            name="new_space_zay-1007_45"
            geometry={nodes['new_space_zay-1007_45'].geometry}
            material={materials['Material.112']}
          />
          <mesh
            name="new_space_zay-1007_46"
            geometry={nodes['new_space_zay-1007_46'].geometry}
            material={materials['Material.113']}
          />
          <mesh
            name="new_space_zay-1007_47"
            geometry={nodes['new_space_zay-1007_47'].geometry}
            material={materials['Material.114']}
          />
          <mesh
            name="new_space_zay-1007_48"
            geometry={nodes['new_space_zay-1007_48'].geometry}
            material={materials['Material.115']}
          />
        </group>
        <mesh
          name="new_space_zay-6004"
          geometry={nodes['new_space_zay-6004'].geometry}
          material={materials['Material.116']}
          position={[9.7772, -3.3549, -37.1926]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6005"
          geometry={nodes['new_space_zay-6005'].geometry}
          material={materials['Material.118']}
          position={[9.7772, -3.3549, -55.0624]}
          rotation={[-Math.PI, -1.5687, -Math.PI]}
        />
        <mesh
          name="new_space_zay-6006"
          geometry={nodes['new_space_zay-6006'].geometry}
          material={materials['Material.120']}
          position={[9.984, -3.3549, -46.4067]}
          rotation={[0, 1.5679, 0]}
        />
        <mesh
          name="new_space_zay-6007"
          geometry={nodes['new_space_zay-6007'].geometry}
          material={materials['Material.122']}
          position={[20.0638, -3.3549, -61.3563]}
          rotation={[0, -0.0002, 0]}
        />
        <mesh
          name="new_space_zay-6008"
          geometry={nodes['new_space_zay-6008'].geometry}
          material={materials['Material.124']}
          position={[0.7146, -3.3549, -61.3563]}
          rotation={[0, -0.0002, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
