/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useEffect, useMemo, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import {useWorld} from "../components/WorldState";
import {useLimiter, useTrimeshCollision} from "spacesvr";
import {useFrame} from "@react-three/fiber";
import {BufferGeometry} from "three";

type GLTFResult = GLTF & {
  nodes: {
    ['new_space_zay-6001']: THREE.Mesh
    ['new_space_zay-6004']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_1']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_2']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_3']: THREE.Mesh
    ['new_space_zay-45-Streetlamp_2003_4']: THREE.Mesh
    ['new_space_zay-50-Air_Vent_1002']: THREE.Mesh
    ['new_space_zay-1']: THREE.Mesh
    Collider: THREE.Mesh
    cube1: THREE.Mesh
    cube1light: THREE.Mesh
    cube2: THREE.Mesh
    cube2light: THREE.Mesh
    cube3: THREE.Mesh
    cube3light: THREE.Mesh
    cube4: THREE.Mesh
    cube4light: THREE.Mesh
    cube5: THREE.Mesh
    cube5light: THREE.Mesh
    cube6: THREE.Mesh
    cube6light: THREE.Mesh
    cube7: THREE.Mesh
    cube7light: THREE.Mesh
    ['new_space_zay-6010']: THREE.Mesh
    ['new_space_zay-6011']: THREE.Mesh
    ['new_space_zay-6014']: THREE.Mesh
    ['new_space_zay-6015']: THREE.Mesh
    ['new_space_zay-6003']: THREE.Mesh
    ['new_space_zay-6005']: THREE.Mesh
    ['new_space_zay-6006']: THREE.Mesh
    ['new_space_zay-6018']: THREE.Mesh
    ['new_space_zay-6019']: THREE.Mesh
    ['new_space_zay-6022']: THREE.Mesh
    ['new_space_zay-6002']: THREE.Mesh
    ['new_space_zay-6046_1']: THREE.Mesh
    ['new_space_zay-6046_2']: THREE.Mesh
    ['new_space_zay-6046_3']: THREE.Mesh
    ['new_space_zay-6046_4']: THREE.Mesh
    ['new_space_zay-6046_5']: THREE.Mesh
    ['new_space_zay-6046_6']: THREE.Mesh
    ['new_space_zay-6046_7']: THREE.Mesh
    ['new_space_zay-6046_8']: THREE.Mesh
    ['new_space_zay-6046_9']: THREE.Mesh
    ['new_space_zay-6046_10']: THREE.Mesh
    ['new_space_zay-6046_11']: THREE.Mesh
    ['new_space_zay-6046_12']: THREE.Mesh
    ['new_space_zay-6046_13']: THREE.Mesh
    ['new_space_zay-6046_14']: THREE.Mesh
    ['new_space_zay-6046_15']: THREE.Mesh
    ['new_space_zay-6046_16']: THREE.Mesh
    ['new_space_zay-6046_17']: THREE.Mesh
    ['new_space_zay-6046_18']: THREE.Mesh
    ['new_space_zay-6046_19']: THREE.Mesh
    ['new_space_zay-6046_20']: THREE.Mesh
    ['new_space_zay-6046_21']: THREE.Mesh
    ['new_space_zay-6046_22']: THREE.Mesh
    ['new_space_zay-6046_23']: THREE.Mesh
    ['new_space_zay-6046_24']: THREE.Mesh
    ['new_space_zay-6046_25']: THREE.Mesh
    ['new_space_zay-6046_26']: THREE.Mesh
    ['new_space_zay-6046_27']: THREE.Mesh
    ['new_space_zay-6046_28']: THREE.Mesh
    ['new_space_zay-6046_29']: THREE.Mesh
    ['new_space_zay-6046_30']: THREE.Mesh
    ['new_space_zay-6046_31']: THREE.Mesh
    ['new_space_zay-6046_32']: THREE.Mesh
    ['new_space_zay-6046_33']: THREE.Mesh
  }
  materials: {
    ['Material.075']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    ['Material.076']: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.087']: THREE.MeshStandardMaterial
    ['Material.139']: THREE.MeshStandardMaterial
    ['Material.096']: THREE.MeshStandardMaterial
    ['Material.091']: THREE.MeshStandardMaterial
    ['Material.099']: THREE.MeshStandardMaterial
    ['Material.098']: THREE.MeshStandardMaterial
    ['Material.097']: THREE.MeshStandardMaterial
    ['Material.102']: THREE.MeshStandardMaterial
    ['Material.101']: THREE.MeshStandardMaterial
    ['Material.100']: THREE.MeshStandardMaterial
    ['Material.107']: THREE.MeshStandardMaterial
    ['Material.106']: THREE.MeshStandardMaterial
    ['Material.105']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.109']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
    ['Material.113']: THREE.MeshStandardMaterial
    ['Material.112']: THREE.MeshStandardMaterial
    ['Material.111']: THREE.MeshStandardMaterial
    ['Material.123']: THREE.MeshStandardMaterial
    ['Material.115']: THREE.MeshStandardMaterial
    ['Material.114']: THREE.MeshStandardMaterial
    ['Material.127']: THREE.MeshStandardMaterial
    ['Material.126']: THREE.MeshStandardMaterial
    ['Material.125']: THREE.MeshStandardMaterial
    ['Material.133']: THREE.MeshStandardMaterial
    ['Material.132']: THREE.MeshStandardMaterial
    ['Material.128']: THREE.MeshStandardMaterial
    ['Material.136']: THREE.MeshStandardMaterial
    ['Material.135']: THREE.MeshStandardMaterial
    ['Material.134']: THREE.MeshStandardMaterial
    ['Material.138']: THREE.MeshStandardMaterial
    ['Material.137']: THREE.MeshStandardMaterial
    ['Material.090']: THREE.MeshStandardMaterial
  }
}

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/station-1648353087/station.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {

  const { bloomObjects, setBloomObjects } = useWorld();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult
  const group = useRef<THREE.Group>(),
    cube1 = useRef<THREE.Mesh>(),
    cube2 = useRef<THREE.Mesh>(),
    cube3 = useRef<THREE.Mesh>(),
    cube4 = useRef<THREE.Mesh>(),
    cube5 = useRef<THREE.Mesh>(),
    cube6 = useRef<THREE.Mesh>(),
    cube7 = useRef<THREE.Mesh>(),
    lightMesh1 = useRef<THREE.Mesh>(),
    lightMesh2 = useRef<THREE.Mesh>(),
    lightMesh3 = useRef<THREE.Mesh>(),
    lightMesh4 = useRef<THREE.Mesh>(),
    lightMesh5 = useRef<THREE.Mesh>(),
    lightMesh6 = useRef<THREE.Mesh>(),
    lightMesh7 = useRef<THREE.Mesh>();

  useEffect(() => {
    setBloomObjects([...bloomObjects, lightMesh1, lightMesh2, lightMesh3, lightMesh4, lightMesh5, lightMesh6, lightMesh7])
  }, [])

  const limiter = useLimiter(30);
  useFrame(({ clock }, delta) => {
    if (!limiter.isReady(clock)
      || !cube1.current
      || !cube2.current
      || !cube3.current
      || !cube4.current
      || !cube5.current
      || !cube6.current
      || !cube7.current
      || !lightMesh1.current
      || !lightMesh2.current
      || !lightMesh3.current
      || !lightMesh4.current
      || !lightMesh5.current
      || !lightMesh6.current
      || !lightMesh7.current
    ) return;
    cube1.current.rotation.x += delta/5;
    cube2.current.rotation.x -= delta/5;
    cube3.current.rotation.x += delta/5;
    cube4.current.rotation.x += delta/5.1;
    cube5.current.rotation.x -= delta/5;
    cube6.current.rotation.x -= delta/5.1;
    cube7.current.rotation.x += delta/5;
    lightMesh1.current.rotation.x = cube1.current.rotation.x;
    lightMesh2.current.rotation.x = cube2.current.rotation.x;
    lightMesh3.current.rotation.x = cube3.current.rotation.x;
    lightMesh4.current.rotation.x = cube4.current.rotation.x;
    lightMesh5.current.rotation.x = cube5.current.rotation.x;
    lightMesh6.current.rotation.x = cube6.current.rotation.x;
    lightMesh7.current.rotation.x = cube7.current.rotation.x;
  })

  const glassMat = new THREE.MeshPhysicalMaterial({
    metalness: 0.75,
    roughness: 1,
    envMapIntensity: 0.9,
    clearcoat: 1,
    transparent: true,
    transmission: 1,
    opacity: 1,
    reflectivity: 0.5,
    sheen: new THREE.Color("black")
  })

  useTrimeshCollision((nodes["Collider"].geometry as BufferGeometry)
    .clone()
    .scale(39.137, 0.3651, 56.7515)
    .translate(4.0458, 0.2531, -33.008)
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="new_space_zay-6001"
          geometry={nodes['new_space_zay-6001'].geometry}
          material={nodes['new_space_zay-6001'].material}
          position={[-0.055, -3.3299, -14.3641]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6004"
          geometry={nodes['new_space_zay-6004'].geometry}
          material={nodes['new_space_zay-6004'].material}
          position={[-0.055, -3.3299, -14.3641]}
          rotation={[0, -1.5701, 0]}
        />
        <group name="lights" position={[-0.9446, 2.8784, -14.2171]} rotation={[0, 1.5649, 0]}>
          <mesh
            name="new_space_zay-45-Streetlamp_2003"
            geometry={nodes['new_space_zay-45-Streetlamp_2003'].geometry}
            material={materials['Material.055']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_1"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_1'].geometry}
            material={materials['Material.084']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_2"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_2'].geometry}
            material={materials['Material.121']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_3"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_3'].geometry}
            material={materials['Material.129']}
          />
          <mesh
            name="new_space_zay-45-Streetlamp_2003_4"
            geometry={nodes['new_space_zay-45-Streetlamp_2003_4'].geometry}
            material={materials['Material.130']}
          />
        </group>
        <mesh
          name="new_space_zay-50-Air_Vent_1002"
          geometry={nodes['new_space_zay-50-Air_Vent_1002'].geometry}
          material={materials['Material.088']}
          position={[-5.9772, -2.4217, -30.111]}
          rotation={[3.1371, 1.5685, 0]}
        />
        <mesh
          name="new_space_zay-1"
          geometry={nodes['new_space_zay-1'].geometry}
          material={materials['Material.131']}
          position={[3.5171, 0.3079, -31.3205]}
        />
        <mesh
          ref={cube1}
          name="cube1"
          geometry={nodes.cube1.geometry}
          material={nodes.cube1.material}
          position={[-24.797, 5.6256, -61.4191]}
          rotation={[-2.4313, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh1}
          name="cube1light"
          geometry={nodes.cube1light.geometry}
          material={nodes.cube1light.material}
          position={[-24.797, 5.6256, -61.4191]}
          rotation={[-2.4313, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube2}
          name="cube2"
          geometry={nodes.cube2.geometry}
          material={nodes.cube2.material}
          position={[-14.7537, 5.6256, -61.4191]}
          rotation={[0.0697, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh2}
          name="cube2light"
          geometry={nodes.cube2light.geometry}
          material={nodes.cube2light.material}
          position={[-14.7537, 5.6256, -61.4191]}
          rotation={[0.0697, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube3}
          name="cube3"
          geometry={nodes.cube3.geometry}
          material={nodes.cube3.material}
          position={[-4.6635, 5.6256, -61.4191]}
          rotation={[2.7674, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh3}
          name="cube3light"
          geometry={nodes.cube3light.geometry}
          material={nodes.cube3light.material}
          position={[-4.6635, 5.6256, -61.4191]}
          rotation={[2.7674, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube4}
          name="cube4"
          geometry={nodes.cube4.geometry}
          material={nodes.cube4.material}
          position={[5.3608, 5.6256, -61.4191]}
          rotation={[-1.3832, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh4}
          name="cube4light"
          geometry={nodes.cube4light.geometry}
          material={nodes.cube4light.material}
          position={[5.3608, 5.6256, -61.4191]}
          rotation={[-1.3832, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube5}
          name="cube5"
          geometry={nodes.cube5.geometry}
          material={nodes.cube5.material}
          position={[15.3836, 5.6256, -61.4191]}
          rotation={[2.1326, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh5}
          name="cube5light"
          geometry={nodes.cube5light.geometry}
          material={nodes.cube5light.material}
          position={[15.3836, 5.6256, -61.4191]}
          rotation={[2.1326, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube6}
          name="cube6"
          geometry={nodes.cube6.geometry}
          material={nodes.cube6.material}
          position={[25.4678, 5.6256, -61.4191]}
          rotation={[-0.4182, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh6}
          name="cube6light"
          geometry={nodes.cube6light.geometry}
          material={nodes.cube6light.material}
          position={[25.4678, 5.6256, -61.4191]}
          rotation={[-0.4182, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={cube7}
          name="cube7"
          geometry={nodes.cube7.geometry}
          material={nodes.cube7.material}
          position={[35.4726, 5.6256, -61.4191]}
          rotation={[2.5559, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          ref={lightMesh7}
          name="cube7light"
          geometry={nodes.cube7light.geometry}
          material={nodes.cube7light.material}
          position={[35.4726, 5.6256, -61.4191]}
          rotation={[2.5559, 0, 0]}
          scale={[2.0911, 3.0443, 3.008]}
        />
        <mesh
          name="new_space_zay-6010"
          geometry={nodes['new_space_zay-6010'].geometry}
          material={glassMat}
          position={[12.9675, -3.3299, -29.9691]}
        />
        <mesh
          name="new_space_zay-6011"
          geometry={nodes['new_space_zay-6011'].geometry}
          material={glassMat}
          position={[5.4579, -3.3299, -30.0206]}
        />
        <mesh
          name="new_space_zay-6014"
          geometry={nodes['new_space_zay-6014'].geometry}
          material={glassMat}
          position={[-2.1313, -3.3299, -29.9286]}
        />
        <mesh
          name="new_space_zay-6015"
          geometry={nodes['new_space_zay-6015'].geometry}
          material={glassMat}
          position={[-0.0593, -3.3299, -22.4768]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6003"
          geometry={nodes['new_space_zay-6003'].geometry}
          material={glassMat}
          position={[-0.0593, -3.3299, -6.6022]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6005"
          geometry={nodes['new_space_zay-6005'].geometry}
          material={glassMat}
          position={[9.8094, -3.3299, -37.6488]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6006"
          geometry={nodes['new_space_zay-6006'].geometry}
          material={glassMat}
          position={[9.7689, -3.3299, -46.1483]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6018"
          geometry={nodes['new_space_zay-6018'].geometry}
          material={glassMat}
          position={[9.7689, -3.3299, -55.5346]}
          rotation={[0, -1.5701, 0]}
        />
        <mesh
          name="new_space_zay-6019"
          geometry={nodes['new_space_zay-6019'].geometry}
          material={glassMat}
          position={[20.1773, -3.3299, -61.4222]}
        />
        <mesh
          name="new_space_zay-6022"
          geometry={nodes['new_space_zay-6022'].geometry}
          material={glassMat}
          position={[0.4637, -3.3299, -61.4222]}
        />
        <mesh
          name="new_space_zay-6002"
          geometry={nodes['new_space_zay-6002'].geometry}
          material={glassMat}
          position={[-0.0593, -3.3299, -14.3641]}
          rotation={[0, -1.5701, 0]}
        />
        <group name="new_space_zay-6046" position={[20.1552, -78.8953, -61.4325]} rotation={[0, -1.5701, 0]}>
          <mesh
            name="new_space_zay-6046_1"
            geometry={nodes['new_space_zay-6046_1'].geometry}
            material={materials['Material.139']}
          />
          <mesh
            name="new_space_zay-6046_2"
            geometry={nodes['new_space_zay-6046_2'].geometry}
            material={materials['Material.096']}
          />
          <mesh
            name="new_space_zay-6046_3"
            geometry={nodes['new_space_zay-6046_3'].geometry}
            material={materials['Material.091']}
          />
          <mesh
            name="new_space_zay-6046_4"
            geometry={nodes['new_space_zay-6046_4'].geometry}
            material={materials['Material.099']}
          />
          <mesh
            name="new_space_zay-6046_5"
            geometry={nodes['new_space_zay-6046_5'].geometry}
            material={materials['Material.098']}
          />
          <mesh
            name="new_space_zay-6046_6"
            geometry={nodes['new_space_zay-6046_6'].geometry}
            material={materials['Material.097']}
          />
          <mesh
            name="new_space_zay-6046_7"
            geometry={nodes['new_space_zay-6046_7'].geometry}
            material={materials['Material.102']}
          />
          <mesh
            name="new_space_zay-6046_8"
            geometry={nodes['new_space_zay-6046_8'].geometry}
            material={materials['Material.101']}
          />
          <mesh
            name="new_space_zay-6046_9"
            geometry={nodes['new_space_zay-6046_9'].geometry}
            material={materials['Material.100']}
          />
          <mesh
            name="new_space_zay-6046_10"
            geometry={nodes['new_space_zay-6046_10'].geometry}
            material={materials['Material.107']}
          />
          <mesh
            name="new_space_zay-6046_11"
            geometry={nodes['new_space_zay-6046_11'].geometry}
            material={materials['Material.106']}
          />
          <mesh
            name="new_space_zay-6046_12"
            geometry={nodes['new_space_zay-6046_12'].geometry}
            material={materials['Material.105']}
          />
          <mesh
            name="new_space_zay-6046_13"
            geometry={nodes['new_space_zay-6046_13'].geometry}
            material={materials['Material.110']}
          />
          <mesh
            name="new_space_zay-6046_14"
            geometry={nodes['new_space_zay-6046_14'].geometry}
            material={materials['Material.109']}
          />
          <mesh
            name="new_space_zay-6046_15"
            geometry={nodes['new_space_zay-6046_15'].geometry}
            material={materials['Material.108']}
          />
          <mesh
            name="new_space_zay-6046_16"
            geometry={nodes['new_space_zay-6046_16'].geometry}
            material={materials['Material.113']}
          />
          <mesh
            name="new_space_zay-6046_17"
            geometry={nodes['new_space_zay-6046_17'].geometry}
            material={materials['Material.112']}
          />
          <mesh
            name="new_space_zay-6046_18"
            geometry={nodes['new_space_zay-6046_18'].geometry}
            material={materials['Material.111']}
          />
          <mesh
            name="new_space_zay-6046_19"
            geometry={nodes['new_space_zay-6046_19'].geometry}
            material={materials['Material.123']}
          />
          <mesh
            name="new_space_zay-6046_20"
            geometry={nodes['new_space_zay-6046_20'].geometry}
            material={materials['Material.115']}
          />
          <mesh
            name="new_space_zay-6046_21"
            geometry={nodes['new_space_zay-6046_21'].geometry}
            material={materials['Material.114']}
          />
          <mesh
            name="new_space_zay-6046_22"
            geometry={nodes['new_space_zay-6046_22'].geometry}
            material={materials['Material.127']}
          />
          <mesh
            name="new_space_zay-6046_23"
            geometry={nodes['new_space_zay-6046_23'].geometry}
            material={materials['Material.126']}
          />
          <mesh
            name="new_space_zay-6046_24"
            geometry={nodes['new_space_zay-6046_24'].geometry}
            material={materials['Material.125']}
          />
          <mesh
            name="new_space_zay-6046_25"
            geometry={nodes['new_space_zay-6046_25'].geometry}
            material={materials['Material.133']}
          />
          <mesh
            name="new_space_zay-6046_26"
            geometry={nodes['new_space_zay-6046_26'].geometry}
            material={materials['Material.132']}
          />
          <mesh
            name="new_space_zay-6046_27"
            geometry={nodes['new_space_zay-6046_27'].geometry}
            material={materials['Material.128']}
          />
          <mesh
            name="new_space_zay-6046_28"
            geometry={nodes['new_space_zay-6046_28'].geometry}
            material={materials['Material.136']}
          />
          <mesh
            name="new_space_zay-6046_29"
            geometry={nodes['new_space_zay-6046_29'].geometry}
            material={materials['Material.135']}
          />
          <mesh
            name="new_space_zay-6046_30"
            geometry={nodes['new_space_zay-6046_30'].geometry}
            material={materials['Material.134']}
          />
          <mesh
            name="new_space_zay-6046_31"
            geometry={nodes['new_space_zay-6046_31'].geometry}
            material={materials['Material.138']}
          />
          <mesh
            name="new_space_zay-6046_32"
            geometry={nodes['new_space_zay-6046_32'].geometry}
            material={materials['Material.137']}
          />
          <mesh
            name="new_space_zay-6046_33"
            geometry={nodes['new_space_zay-6046_33'].geometry}
            material={materials['Material.090']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
