/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh
    Torus: THREE.Mesh
    Icosphere: THREE.Mesh
    Plane: THREE.Mesh
    poof: THREE.Mesh
    floorsparks: THREE.Mesh
  }
  materials: {
    sparks: THREE.MeshStandardMaterial
    frame: THREE.MeshStandardMaterial
    plane: THREE.MeshStandardMaterial
  }
}

type ActionName = 'EmptyAction' | 'Plane.001Action'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

const FILE_URL = "https://d1p3v0j4bqcb21.cloudfront.net/models/portal-1635371188/portal.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(FILE_URL) as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera" position={[0, 4.71, 52.63]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Empty" position={[0, 3.5429, 0]} scale={0}>
          <mesh
            name="Circle"
            geometry={nodes.Circle.geometry}
            material={nodes.Circle.material}
            position={[0, 0, 0.078]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={2.5}
          />
          <mesh
            name="Torus"
            geometry={nodes.Torus.geometry}
            material={materials.frame}
            position={[0, 0, -0.0436]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={2.5275}
          />
        </group>
        <mesh
          name="Icosphere"
          geometry={nodes.Icosphere.geometry}
          material={nodes.Icosphere.material}
          position={[20.4116, 0.6839, 0]}
          scale={0.0986}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.plane}
          position={[0, -1.6169, 0]}
          scale={16.6534}
        />
        <mesh
          name="poof"
          geometry={nodes.poof.geometry}
          material={nodes.poof.material}
          position={[0, 3.544, 0]}
          rotation={[1.9679, -1.0713, 0.0507]}
          scale={[0.108, 0.108, 0.108]}
        />
        <mesh
          name="floorsparks"
          geometry={nodes.floorsparks.geometry}
          material={nodes.floorsparks.material}
          position={[0, -1.6169, 0.2531]}
          scale={0}
        />
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
