/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    cable002: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere007_1: THREE.Mesh
    Icosphere007_2: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    leaf: THREE.MeshStandardMaterial
    ['TREE!_BARK1_.002']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/tree5.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Catenary" position={[-20.7264, 20.9549, -9.0286]} />
        <mesh
          name="cable002"
          geometry={nodes.cable002.geometry}
          material={nodes.cable002.material}
          position={[33.0758, 7.5904, -0.4693]}
          rotation={[0, 0, -0.4231]}
          scale={[0.5677, 0.5677, 0.5677]}
        />
        <group name="Icosphere004" position={[40.834, 24.5874, 3.1751]} scale={[15.2491, 6.163, 7.9172]}>
          <mesh name="Icosphere007" geometry={nodes.Icosphere007.geometry} material={materials.leaf} />
          <mesh
            name="Icosphere007_1"
            geometry={nodes.Icosphere007_1.geometry}
            material={materials['TREE!_BARK1_.002']}
          />
          <mesh
            name="Icosphere007_2"
            geometry={nodes.Icosphere007_2.geometry}
            material={nodes.Icosphere007_2.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree5.glb')
